// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/dashify/chartgen from internal/framework/dashify/charts/schemas/*.yml; DO NOT EDIT.

package charts

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

const MetricsClusterMapName = "metrics_cluster_map"
const MetricsListName = "metrics_list"
const MetricsSingleValueName = "metrics_single_value"
const MetricsTableName = "metrics_table"
const MetricsTimeSeriesName = "metrics_time_series"
const TextName = "text"

func ContentBlocks() map[string]schema.Block {
	return map[string]schema.Block{
		MetricsClusterMapName:  schema.SingleNestedBlock{MarkdownDescription: "Terraform-facing schema for Dashify's o11y:ClusterMap chart - a grid of colored cells, one per source, confirmed to be the real migration target for classic `signalfx_heatmap_chart` (NOT Dashify's own newer, unrelated `o11y:Heatmap` element, a time-bucketed histogram with ~0 classic usage; see convertHeatmap.ts in app-modern-dashboards, which converts a classic Heatmap chart's colorBy/colorScale/colorRange/groupBy straight into `<o11y:ClusterMap>`). Scoped to what the 171 existing signalfx_heatmap_chart resources in terraform-monitoring actually set, cross-checked against ClusterMapConfigPanel.tsx (the real Dashify editor for this chart type).", Attributes: MetricsClusterMapSchemaAttributes()},
		MetricsListName:        schema.SingleNestedBlock{MarkdownDescription: "Terraform-facing schema for Dashify's o11y:List chart, scoped to what the 1806 existing signalfx_list_chart resources in terraform-monitoring actually set. Fields with no classic equivalent, plus deprecated/runtime-derived/ JSON-only ones, are intentionally omitted.", Attributes: MetricsListSchemaAttributes()},
		MetricsSingleValueName: schema.SingleNestedBlock{MarkdownDescription: "Terraform-facing schema for Dashify's o11y:SingleValue chart, scoped to what the 1240 existing signalfx_single_value_chart resources in terraform-monitoring actually set. Fields with no classic equivalent, plus deprecated/runtime-derived/JSON-only ones, are intentionally omitted.", Attributes: MetricsSingleValueSchemaAttributes()},
		MetricsTableName:       schema.SingleNestedBlock{MarkdownDescription: "Terraform-facing schema for Dashify's o11y:TableChart chart (not o11y:Table - confirmed against the real element tag), scoped to what the 103 existing signalfx_table_chart resources in terraform-monitoring actually set. This is the rarest classic chart type by a wide margin (0.5% of all charts), so the schema is deliberately minimal.", Attributes: MetricsTableSchemaAttributes()},
		MetricsTimeSeriesName:  schema.SingleNestedBlock{MarkdownDescription: "Basic Terraform-facing schema for Dashify's o11y:TimeSeriesChart. It covers the common editor-supported path: SignalFlow, line/area/column rendering, stacking, legends, markers, two Y axes, and per-series display overrides. Advanced or unstable chart properties remain available through an observability_template rather than an open-ended merge bag.", Attributes: MetricsTimeSeriesSchemaAttributes()},
		TextName:               schema.SingleNestedBlock{MarkdownDescription: "Terraform-facing schema for Dashify's o11y:Text chart - a markdown/notes widget with no metric plumbing. Scoped to the 1241 existing signalfx_text_chart resources in terraform-monitoring, the largest single chart-type gap before this schema existed: text charts are the third most common classic chart type after time and list charts, mostly used for runbook/notes widgets.", Attributes: TextSchemaAttributes()},
	}
}

func NameForElement(tag string) (string, bool) {
	switch tag {
	case "<o11y:ClusterMap>":
		return MetricsClusterMapName, true
	case "<o11y:List>":
		return MetricsListName, true
	case "<o11y:SingleValue>":
		return MetricsSingleValueName, true
	case "<o11y:TableChart>":
		return MetricsTableName, true
	case "<o11y:TimeSeriesChart>":
		return MetricsTimeSeriesName, true
	case "<o11y:Text>":
		return TextName, true
	default:
		return "", false
	}
}

func IsSupportedElement(tag string) bool { _, ok := NameForElement(tag); return ok }

func normalizationRules(tag string) []normalizationRule {
	switch tag {
	case "<o11y:ClusterMap>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
		}
	case "<o11y:List>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "publishedStreams", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "publishedStreams", "*", "unit"}, Prefix: []string{"chart", "publishedStreams", "*", "prefix"}, Suffix: []string{"chart", "publishedStreams", "*", "suffix"}},
		}
	case "<o11y:SingleValue>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "fallback", Target: []string{"chart", "maximumFractionDigits"}, Source: []string{"chart", "numberPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "single_value_publish_label_options", Target: []string{"chart", "displayUnit"}, Source: []string{"chart", "publishLabelOptions"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
		}
	case "<o11y:TableChart>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "wrap_scalar_array", Target: []string{"chart", "groupBy"}, Source: []string{}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "columns", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "columns", "*", "unit"}, Prefix: []string{"chart", "columns", "*", "prefix"}, Suffix: []string{"chart", "columns", "*", "suffix"}},
		}
	case "<o11y:TimeSeriesChart>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "chartOptions", "maximumSignificantDigits"}, Source: []string{"chart", "chartOptions", "axisPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "fallback", Target: []string{"chart", "seriesOptions", "*", "maximumSignificantDigits"}, Source: []string{"chart", "seriesOptions", "*", "precision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "seriesOptions", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "seriesOptions", "*", "valueUnit"}, Prefix: []string{"chart", "seriesOptions", "*", "valuePrefix"}, Suffix: []string{"chart", "seriesOptions", "*", "valueSuffix"}},
		}
	default:
		return nil
	}
}

// ParseContent parses a recognized chart without mutating spec. TypedSafe is
// true only when generated validation passes and rebuilding the model is
// semantically identical after the explicitly approved normalizations.
func ParseContent(tag string, spec map[string]any) (Entry, ParseMetadata, error) {
	metadata := ParseMetadata{ElementTag: tag}
	name, ok := NameForElement(tag)
	if !ok {
		return Entry{}, metadata, fmt.Errorf("unsupported chart element %q", tag)
	}
	original := cloneSpecMap(spec)
	metadata.ValidationErrors = append(metadata.ValidationErrors, validateElementContract(tag, original)...)
	normalized := cloneSpecMap(original)
	normalizations, err := applyNormalizations(normalized, normalizationRules(tag))
	if err != nil {
		return Entry{}, metadata, err
	}
	metadata.Normalizations = normalizations
	working := cloneSpecMap(normalized)
	var content Content
	switch tag {
	case "<o11y:ClusterMap>":
		model, parseErr := ParseMetricsClusterMapSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:List>":
		model, parseErr := ParseMetricsListSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:SingleValue>":
		model, parseErr := ParseMetricsSingleValueSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:TableChart>":
		model, parseErr := ParseMetricsTableSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:TimeSeriesChart>":
		model, parseErr := ParseMetricsTimeSeriesSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:Text>":
		model, parseErr := ParseTextSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	}
	entry := Entry{Name: name, Content: content}
	metadata.Leftovers = Leftovers("", working)
	metadata.MissingRequiredFields = content.MissingRequiredFields()
	metadata.ValidationErrors = append(metadata.ValidationErrors, content.ValidationErrors()...)
	metadata.Lossless = len(metadata.Leftovers) == 0 && len(metadata.MissingRequiredFields) == 0 && len(metadata.ValidationErrors) == 0 && semanticallyEqualSpec(normalized, content.BuildSpec())
	return entry, metadata, nil
}
