// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/dashify/chartgen from internal/framework/dashify/charts/schemas/*.yml; DO NOT EDIT.

package charts

import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

const MetricsClusterMapName = "metrics_cluster_map"
const MetricsListName = "metrics_list"
const MetricsSingleValueName = "metrics_single_value"
const MetricsTableName = "metrics_table"
const MetricsTimeSeriesName = "metrics_time_series"
const TextName = "text"

type Fields struct {
	MetricsClusterMap  *MetricsClusterMapModel  `tfsdk:"metrics_cluster_map"`
	MetricsList        *MetricsListModel        `tfsdk:"metrics_list"`
	MetricsSingleValue *MetricsSingleValueModel `tfsdk:"metrics_single_value"`
	MetricsTable       *MetricsTableModel       `tfsdk:"metrics_table"`
	MetricsTimeSeries  *MetricsTimeSeriesModel  `tfsdk:"metrics_time_series"`
	Text               *TextModel               `tfsdk:"text"`
}

func (f Fields) Entries() []Entry {
	var entries []Entry
	if f.MetricsClusterMap != nil {
		entries = append(entries, Entry{Name: MetricsClusterMapName, Content: f.MetricsClusterMap})
	}
	if f.MetricsList != nil {
		entries = append(entries, Entry{Name: MetricsListName, Content: f.MetricsList})
	}
	if f.MetricsSingleValue != nil {
		entries = append(entries, Entry{Name: MetricsSingleValueName, Content: f.MetricsSingleValue})
	}
	if f.MetricsTable != nil {
		entries = append(entries, Entry{Name: MetricsTableName, Content: f.MetricsTable})
	}
	if f.MetricsTimeSeries != nil {
		entries = append(entries, Entry{Name: MetricsTimeSeriesName, Content: f.MetricsTimeSeries})
	}
	if f.Text != nil {
		entries = append(entries, Entry{Name: TextName, Content: f.Text})
	}
	return entries
}

func (f *Fields) SetEntries(entries []Entry) error {
	f.MetricsClusterMap = nil
	f.MetricsList = nil
	f.MetricsSingleValue = nil
	f.MetricsTable = nil
	f.MetricsTimeSeries = nil
	f.Text = nil
	for _, entry := range entries {
		switch entry.Name {
		case MetricsClusterMapName:
			model, ok := entry.Content.(*MetricsClusterMapModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsClusterMapModel", entry.Name, entry.Content)
			}
			if f.MetricsClusterMap != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsClusterMap = model
		case MetricsListName:
			model, ok := entry.Content.(*MetricsListModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsListModel", entry.Name, entry.Content)
			}
			if f.MetricsList != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsList = model
		case MetricsSingleValueName:
			model, ok := entry.Content.(*MetricsSingleValueModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsSingleValueModel", entry.Name, entry.Content)
			}
			if f.MetricsSingleValue != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsSingleValue = model
		case MetricsTableName:
			model, ok := entry.Content.(*MetricsTableModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsTableModel", entry.Name, entry.Content)
			}
			if f.MetricsTable != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsTable = model
		case MetricsTimeSeriesName:
			model, ok := entry.Content.(*MetricsTimeSeriesModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsTimeSeriesModel", entry.Name, entry.Content)
			}
			if f.MetricsTimeSeries != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsTimeSeries = model
		case TextName:
			model, ok := entry.Content.(*TextModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.TextModel", entry.Name, entry.Content)
			}
			if f.Text != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.Text = model
		default:
			return fmt.Errorf("unsupported chart entry %q", entry.Name)
		}
	}
	return nil
}

func ContentBlocks() map[string]schema.Block {
	return map[string]schema.Block{
		MetricsClusterMapName:  schema.SingleNestedBlock{MarkdownDescription: "A grid of colored cells, one cell per source, colored by the metric value. This is the Dashify equivalent of the classic `signalfx_heatmap_chart` resource. Cells are laid out in query-result order and there is no chart-level sort option, so encode any required ordering in the SignalFlow `program` itself, for example with `top()`.", Attributes: MetricsClusterMapSchemaAttributes()},
		MetricsListName:        schema.SingleNestedBlock{MarkdownDescription: "A list of metric values, one row per series, with optional sorting and a secondary sparkline or gauge per row. This is the Dashify equivalent of the classic `signalfx_list_chart` resource. Note that `color_by` and `color_scale` render correctly and survive import, but the Dashify UI does not write them back when saving, so editing this chart in the UI will drop them.", Attributes: MetricsListSchemaAttributes()},
		MetricsSingleValueName: schema.SingleNestedBlock{MarkdownDescription: "A single current metric value, optionally paired with a sparkline or a radial/linear gauge and a color scale. This is the Dashify equivalent of the classic `signalfx_single_value_chart` resource.", Attributes: MetricsSingleValueSchemaAttributes()},
		MetricsTableName:       schema.SingleNestedBlock{MarkdownDescription: "A table of metric values with configurable columns and grouping. This is the Dashify equivalent of the classic `signalfx_table_chart` resource.", Attributes: MetricsTableSchemaAttributes()},
		MetricsTimeSeriesName:  schema.SingleNestedBlock{MarkdownDescription: "A time-series chart plotting SignalFlow output over time. Supports line, area, and column rendering, stacking, legends, markers, two Y axes, and per-series display overrides. This is the Dashify equivalent of the classic `signalfx_time_chart` resource. Chart properties outside this set are not modeled here; use `signalfx_observability_template` to author them directly.", Attributes: MetricsTimeSeriesSchemaAttributes()},
		TextName:               schema.SingleNestedBlock{MarkdownDescription: "A markdown notes widget with no metric plumbing, commonly used for runbook links and dashboard annotations. This is the Dashify equivalent of the classic `signalfx_text_chart` resource.", Attributes: TextSchemaAttributes()},
	}
}

func NameForElement(tag string) (string, bool) {
	switch tag {
	case "<o11y:ClusterMap>":
		return MetricsClusterMapName, true
	case "<o11y:List>":
		return MetricsListName, true
	case "<o11y:SingleValue>":
		return MetricsSingleValueName, true
	case "<o11y:TableChart>":
		return MetricsTableName, true
	case "<o11y:TimeSeriesChart>":
		return MetricsTimeSeriesName, true
	case "<o11y:Text>":
		return TextName, true
	default:
		return "", false
	}
}

func IsSupportedElement(tag string) bool { _, ok := NameForElement(tag); return ok }

func normalizationRules(tag string) []normalizationRule {
	switch tag {
	case "<o11y:ClusterMap>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
		}
	case "<o11y:List>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "publishedStreams", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "publishedStreams", "*", "unit"}, Prefix: []string{"chart", "publishedStreams", "*", "prefix"}, Suffix: []string{"chart", "publishedStreams", "*", "suffix"}},
		}
	case "<o11y:SingleValue>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "fallback", Target: []string{"chart", "maximumFractionDigits"}, Source: []string{"chart", "numberPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "single_value_publish_label_options", Target: []string{"chart", "displayUnit"}, Source: []string{"chart", "publishLabelOptions"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
		}
	case "<o11y:TableChart>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "maximumSignificantDigits"}, Source: []string{"chart", "maxPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "wrap_scalar_array", Target: []string{"chart", "groupBy"}, Source: []string{}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "columns", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "columns", "*", "unit"}, Prefix: []string{"chart", "columns", "*", "prefix"}, Suffix: []string{"chart", "columns", "*", "suffix"}},
		}
	case "<o11y:TimeSeriesChart>":
		return []normalizationRule{
			{Kind: "fallback", Target: []string{"chart", "chartOptions", "maximumSignificantDigits"}, Source: []string{"chart", "chartOptions", "axisPrecision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "fallback", Target: []string{"chart", "seriesOptions", "*", "maximumSignificantDigits"}, Source: []string{"chart", "seriesOptions", "*", "precision"}, Unit: []string{}, Prefix: []string{}, Suffix: []string{}},
			{Kind: "display_unit", Target: []string{"chart", "seriesOptions", "*", "displayUnit"}, Source: []string{}, Unit: []string{"chart", "seriesOptions", "*", "valueUnit"}, Prefix: []string{"chart", "seriesOptions", "*", "valuePrefix"}, Suffix: []string{"chart", "seriesOptions", "*", "valueSuffix"}},
		}
	default:
		return nil
	}
}

// ParseContent parses a recognized chart without mutating spec. TypedSafe is
// true only when generated validation passes and rebuilding the model is
// semantically identical after the explicitly approved normalizations.
func ParseContent(tag string, spec map[string]any) (Entry, ParseMetadata, error) {
	metadata := ParseMetadata{ElementTag: tag}
	name, ok := NameForElement(tag)
	if !ok {
		return Entry{}, metadata, fmt.Errorf("unsupported chart element %q", tag)
	}
	normalized := cloneSpecMap(spec)
	normalizations, err := applyNormalizations(normalized, normalizationRules(tag))
	if err != nil {
		return Entry{}, metadata, err
	}
	metadata.Normalizations = normalizations
	working := cloneSpecMap(normalized)
	var content Content
	switch tag {
	case "<o11y:ClusterMap>":
		model, parseErr := ParseMetricsClusterMapSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:List>":
		model, parseErr := ParseMetricsListSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:SingleValue>":
		model, parseErr := ParseMetricsSingleValueSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:TableChart>":
		model, parseErr := ParseMetricsTableSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:TimeSeriesChart>":
		model, parseErr := ParseMetricsTimeSeriesSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	case "<o11y:Text>":
		model, parseErr := ParseTextSpec(working)
		if parseErr != nil {
			return Entry{}, metadata, parseErr
		}
		content = &model
	}
	entry := Entry{Name: name, Content: content}
	metadata.Leftovers = Leftovers("", working)
	metadata.MissingRequiredFields = content.MissingRequiredFields()
	metadata.ValidationErrors = append(metadata.ValidationErrors, content.ValidationErrors()...)
	metadata.Lossless = len(metadata.Leftovers) == 0 && len(metadata.MissingRequiredFields) == 0 && len(metadata.ValidationErrors) == 0 && semanticallyEqualSpec(normalized, content.BuildSpec())
	return entry, metadata, nil
}
