// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/dashify/chartgen from internal/framework/dashify/charts/schemas/*.yml; DO NOT EDIT.

package dashboard

import (
	"fmt"

	"github.com/splunk-terraform/terraform-provider-signalfx/internal/framework/dashify/charts"
)

type dashifyChartFields struct {
	MetricsClusterMap  *charts.MetricsClusterMapModel  `tfsdk:"metrics_cluster_map"`
	MetricsList        *charts.MetricsListModel        `tfsdk:"metrics_list"`
	MetricsSingleValue *charts.MetricsSingleValueModel `tfsdk:"metrics_single_value"`
	MetricsTable       *charts.MetricsTableModel       `tfsdk:"metrics_table"`
	MetricsTimeSeries  *charts.MetricsTimeSeriesModel  `tfsdk:"metrics_time_series"`
	Text               *charts.TextModel               `tfsdk:"text"`
}

func (f dashifyChartFields) chartEntries() []charts.Entry {
	var entries []charts.Entry
	if f.MetricsClusterMap != nil {
		entries = append(entries, charts.Entry{Name: charts.MetricsClusterMapName, Content: f.MetricsClusterMap})
	}
	if f.MetricsList != nil {
		entries = append(entries, charts.Entry{Name: charts.MetricsListName, Content: f.MetricsList})
	}
	if f.MetricsSingleValue != nil {
		entries = append(entries, charts.Entry{Name: charts.MetricsSingleValueName, Content: f.MetricsSingleValue})
	}
	if f.MetricsTable != nil {
		entries = append(entries, charts.Entry{Name: charts.MetricsTableName, Content: f.MetricsTable})
	}
	if f.MetricsTimeSeries != nil {
		entries = append(entries, charts.Entry{Name: charts.MetricsTimeSeriesName, Content: f.MetricsTimeSeries})
	}
	if f.Text != nil {
		entries = append(entries, charts.Entry{Name: charts.TextName, Content: f.Text})
	}
	return entries
}

func (f *dashifyChartFields) setChartEntries(entries []charts.Entry) error {
	f.MetricsClusterMap = nil
	f.MetricsList = nil
	f.MetricsSingleValue = nil
	f.MetricsTable = nil
	f.MetricsTimeSeries = nil
	f.Text = nil
	for _, entry := range entries {
		switch entry.Name {
		case charts.MetricsClusterMapName:
			model, ok := entry.Content.(*charts.MetricsClusterMapModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsClusterMapModel", entry.Name, entry.Content)
			}
			if f.MetricsClusterMap != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsClusterMap = model
		case charts.MetricsListName:
			model, ok := entry.Content.(*charts.MetricsListModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsListModel", entry.Name, entry.Content)
			}
			if f.MetricsList != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsList = model
		case charts.MetricsSingleValueName:
			model, ok := entry.Content.(*charts.MetricsSingleValueModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsSingleValueModel", entry.Name, entry.Content)
			}
			if f.MetricsSingleValue != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsSingleValue = model
		case charts.MetricsTableName:
			model, ok := entry.Content.(*charts.MetricsTableModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsTableModel", entry.Name, entry.Content)
			}
			if f.MetricsTable != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsTable = model
		case charts.MetricsTimeSeriesName:
			model, ok := entry.Content.(*charts.MetricsTimeSeriesModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.MetricsTimeSeriesModel", entry.Name, entry.Content)
			}
			if f.MetricsTimeSeries != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.MetricsTimeSeries = model
		case charts.TextName:
			model, ok := entry.Content.(*charts.TextModel)
			if !ok {
				return fmt.Errorf("chart entry %q has %T content, want *charts.TextModel", entry.Name, entry.Content)
			}
			if f.Text != nil {
				return fmt.Errorf("duplicate chart entry %q", entry.Name)
			}
			f.Text = model
		default:
			return fmt.Errorf("unsupported chart entry %q", entry.Name)
		}
	}
	return nil
}

type dashifyDashboardContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
	Section  *dashifySectionModel  `tfsdk:"section"`
	Group    *dashifyGroupModel    `tfsdk:"group"`
}

type dashifySectionContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
	Group    *dashifyGroupModel    `tfsdk:"group"`
}

type dashifyGroupContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
}
