// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/dashify/chartgen from internal/framework/dashify/charts/schemas/*.yml; DO NOT EDIT.

package dashboard

import "github.com/splunk-terraform/terraform-provider-signalfx/internal/framework/dashify/charts"

type dashifyChartFields = charts.Fields

type dashifyDashboardContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
	Section  *dashifySectionModel  `tfsdk:"section"`
	Group    *dashifyGroupModel    `tfsdk:"group"`
}

type dashifySectionContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
	Group    *dashifyGroupModel    `tfsdk:"group"`
}

type dashifyGroupContainerModel struct {
	Layout *dashifyLayoutModel `tfsdk:"layout"`
	dashifyChartFields
	Template *dashifyTemplateModel `tfsdk:"template"`
}
