// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/observability/chartgen from internal/framework/observability/charts/schemas/metrics_cluster_map.yml; DO NOT EDIT.

package charts

import (
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

type MetricsClusterMapColorRangeModel struct {
	Max     types.Float64 `tfsdk:"max"`
	Min     types.Float64 `tfsdk:"min"`
	Palette types.String  `tfsdk:"palette"`
}

func (p MetricsClusterMapColorRangeModel) buildSpec() map[string]any {
	out := map[string]any{}
	if !p.Max.IsNull() && !p.Max.IsUnknown() {
		setPath(out, []string{"max"}, p.Max.ValueFloat64())
	}
	if !p.Min.IsNull() && !p.Min.IsUnknown() {
		setPath(out, []string{"min"}, p.Min.ValueFloat64())
	}
	if !p.Palette.IsNull() && !p.Palette.IsUnknown() {
		setPath(out, []string{"palette"}, p.Palette.ValueString())
	}
	return out
}

func parseMetricsClusterMapColorRangeModel(spec map[string]any) (MetricsClusterMapColorRangeModel, error) {
	var model MetricsClusterMapColorRangeModel
	var err error
	if model.Max, err = TakeFloat64(spec, []string{"max"}, Scalar); err != nil {
		return model, err
	}
	if model.Min, err = TakeFloat64(spec, []string{"min"}, Scalar); err != nil {
		return model, err
	}
	if model.Palette, err = TakeString(spec, []string{"palette"}, Scalar); err != nil {
		return model, err
	}
	return model, nil
}

func (p MetricsClusterMapColorRangeModel) missingRequiredFields(prefix string) []string {
	var missing []string
	if p.Palette.IsNull() {
		missing = append(missing, prefix+".palette")
	}
	return missing
}

func (p MetricsClusterMapColorRangeModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "max"), p.Max)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "min"), p.Min)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "palette"), p.Palette, true, 0, []string{"temperature", "purple", "cyan"}...)...)
	return validationErrors
}

type MetricsClusterMapColorScaleModel struct {
	Gt           types.Float64 `tfsdk:"gt"`
	Gte          types.Float64 `tfsdk:"gte"`
	Lt           types.Float64 `tfsdk:"lt"`
	Lte          types.Float64 `tfsdk:"lte"`
	PaletteIndex types.Int64   `tfsdk:"palette_index"`
}

func (p MetricsClusterMapColorScaleModel) buildSpec() map[string]any {
	out := map[string]any{}
	if !p.Gt.IsNull() && !p.Gt.IsUnknown() {
		setPath(out, []string{"gt"}, p.Gt.ValueFloat64())
	}
	if !p.Gte.IsNull() && !p.Gte.IsUnknown() {
		setPath(out, []string{"gte"}, p.Gte.ValueFloat64())
	}
	if !p.Lt.IsNull() && !p.Lt.IsUnknown() {
		setPath(out, []string{"lt"}, p.Lt.ValueFloat64())
	}
	if !p.Lte.IsNull() && !p.Lte.IsUnknown() {
		setPath(out, []string{"lte"}, p.Lte.ValueFloat64())
	}
	if !p.PaletteIndex.IsNull() && !p.PaletteIndex.IsUnknown() {
		setPath(out, []string{"paletteIndex"}, p.PaletteIndex.ValueInt64())
	}
	return out
}

func parseMetricsClusterMapColorScaleModel(spec map[string]any) (MetricsClusterMapColorScaleModel, error) {
	var model MetricsClusterMapColorScaleModel
	var err error
	if model.Gt, err = TakeFloat64(spec, []string{"gt"}, Scalar); err != nil {
		return model, err
	}
	if model.Gte, err = TakeFloat64(spec, []string{"gte"}, Scalar); err != nil {
		return model, err
	}
	if model.Lt, err = TakeFloat64(spec, []string{"lt"}, Scalar); err != nil {
		return model, err
	}
	if model.Lte, err = TakeFloat64(spec, []string{"lte"}, Scalar); err != nil {
		return model, err
	}
	if model.PaletteIndex, err = TakeInt64(spec, []string{"paletteIndex"}, Scalar); err != nil {
		return model, err
	}
	return model, nil
}

func (p MetricsClusterMapColorScaleModel) missingRequiredFields(prefix string) []string {
	var missing []string
	return missing
}

func (p MetricsClusterMapColorScaleModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "gt"), p.Gt)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "gte"), p.Gte)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "lt"), p.Lt)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "lte"), p.Lte)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "palette_index"), p.PaletteIndex, int64Pointer(0), int64Pointer(21))...)
	if !p.Gt.IsNull() && !p.Gt.IsUnknown() && !p.Gte.IsNull() && !p.Gte.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "gt"), Message: "conflicts with gte"})
	}
	if !p.Lt.IsNull() && !p.Lt.IsUnknown() && !p.Lte.IsNull() && !p.Lte.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "lt"), Message: "conflicts with lte"})
	}
	return validationErrors
}

type MetricsClusterMapDisplayUnitModel struct {
	Prefix types.String `tfsdk:"prefix"`
	Suffix types.String `tfsdk:"suffix"`
}

func (p MetricsClusterMapDisplayUnitModel) buildSpec() map[string]any {
	out := map[string]any{}
	if !p.Prefix.IsNull() && !p.Prefix.IsUnknown() {
		setPath(out, []string{"prefix"}, p.Prefix.ValueString())
	}
	if !p.Suffix.IsNull() && !p.Suffix.IsUnknown() {
		setPath(out, []string{"suffix"}, p.Suffix.ValueString())
	}
	return out
}

func parseMetricsClusterMapDisplayUnitModel(spec map[string]any) (MetricsClusterMapDisplayUnitModel, error) {
	var model MetricsClusterMapDisplayUnitModel
	var err error
	if model.Prefix, err = TakeString(spec, []string{"prefix"}, Scalar); err != nil {
		return model, err
	}
	if model.Suffix, err = TakeString(spec, []string{"suffix"}, Scalar); err != nil {
		return model, err
	}
	return model, nil
}

func (p MetricsClusterMapDisplayUnitModel) missingRequiredFields(prefix string) []string {
	var missing []string
	return missing
}

func (p MetricsClusterMapDisplayUnitModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "prefix"), p.Prefix, false, 0, []string(nil)...)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "suffix"), p.Suffix, false, 0, []string(nil)...)...)
	if !(!p.Prefix.IsNull() && !p.Prefix.IsUnknown() && p.Prefix.ValueString() != "" || !p.Suffix.IsNull() && !p.Suffix.IsUnknown() && p.Suffix.ValueString() != "") {
		validationErrors = append(validationErrors, ValidationError{Path: prefix, Message: "must set at least one of prefix, suffix"})
	}
	return validationErrors
}

type MetricsClusterMapModel struct {
	ColorBy                  types.String                       `tfsdk:"color_by"`
	ColorRange               *MetricsClusterMapColorRangeModel  `tfsdk:"color_range"`
	ColorScale               []MetricsClusterMapColorScaleModel `tfsdk:"color_scale"`
	Description              types.String                       `tfsdk:"description"`
	DisplayUnit              *MetricsClusterMapDisplayUnitModel `tfsdk:"display_unit"`
	GroupBy                  []types.String                     `tfsdk:"group_by"`
	MaxDelay                 types.Int64                        `tfsdk:"max_delay"`
	MaximumSignificantDigits types.Int64                        `tfsdk:"maximum_significant_digits"`
	MinimumResolution        types.Int64                        `tfsdk:"minimum_resolution"`
	Program                  types.String                       `tfsdk:"program"`
	SampleSize               types.Int64                        `tfsdk:"sample_size"`
	ShowTimestamp            types.Bool                         `tfsdk:"show_timestamp"`
	TimeRange                types.String                       `tfsdk:"time_range"`
	Title                    types.String                       `tfsdk:"title"`
}

func MetricsClusterMapSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"color_by":                   schema.StringAttribute{Optional: true, MarkdownDescription: "How to color each cell: by threshold buckets (`color_scale`) or by a continuous palette range (`color_range`). Must be set to `Scale` for `color_scale` to have any visible effect - it is not inferred from `color_scale` being present. Defaults to `Range` when unset.", Validators: []validator.String{stringvalidator.OneOf("Range", "Scale")}},
		"color_range":                schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "A continuous color palette applied across the cells' actual value range. Only meaningful when `color_by` is `Range`.", Attributes: map[string]schema.Attribute{"max": schema.Float64Attribute{Optional: true, MarkdownDescription: "The value at the top of the palette range. Unset means Auto (derived from the live data's maximum each refresh)."}, "min": schema.Float64Attribute{Optional: true, MarkdownDescription: "The value at the bottom of the palette range. Unset means Auto (derived from the live data's minimum each refresh)."}, "palette": schema.StringAttribute{Required: true, MarkdownDescription: "The named color palette to shade cells with, light to dark.", Validators: []validator.String{stringvalidator.OneOf("temperature", "purple", "cyan")}}}},
		"color_scale":                schema.ListNestedAttribute{Optional: true, MarkdownDescription: "Color bands applied to each cell's value based on which threshold range it falls in. Only meaningful when `color_by` is `Scale`.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{"gt": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's lower bound, exclusive. Mutually exclusive with `gte`."}, "gte": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's lower bound, inclusive. Mutually exclusive with `gt`."}, "lt": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's upper bound, exclusive. Mutually exclusive with `lte`. Not settable in the Dashify editor."}, "lte": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's upper bound, inclusive. Mutually exclusive with `lt`. Not settable in the Dashify editor."}, "palette_index": schema.Int64Attribute{Optional: true, MarkdownDescription: "The palette color index (0-21) to draw this bucket in.", Validators: []validator.Int64{int64validator.AtLeast(0), int64validator.AtMost(21)}}}}, Validators: []validator.List{listvalidator.SizeAtMost(5)}},
		"description":                schema.StringAttribute{Optional: true, MarkdownDescription: "Extended text shown below the title describing the chart's purpose."},
		"display_unit":               schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "A literal prefix and/or suffix to attach to displayed values. At least one of prefix or suffix must be set when this object is present.", Attributes: map[string]schema.Attribute{"prefix": schema.StringAttribute{Optional: true, MarkdownDescription: "Text shown immediately before each displayed value."}, "suffix": schema.StringAttribute{Optional: true, MarkdownDescription: "Text shown immediately after each displayed value."}}},
		"group_by":                   schema.ListAttribute{Optional: true, MarkdownDescription: "Metadata properties to group cells by (in nesting order). At most two.", ElementType: types.StringType, Validators: []validator.List{listvalidator.SizeAtMost(2)}},
		"max_delay":                  schema.Int64Attribute{Optional: true, MarkdownDescription: "Milliseconds to wait for late-arriving data points before charting what has arrived. 0 lets Splunk Observability Cloud choose automatically."},
		"maximum_significant_digits": schema.Int64Attribute{Optional: true, MarkdownDescription: "The number of significant digits to display for values in this chart. Unset lets Splunk Observability Cloud adjust precision to fit the available space. Defaults to `4` when unset.", Validators: []validator.Int64{int64validator.AtLeast(1), int64validator.AtMost(20)}},
		"minimum_resolution":         schema.Int64Attribute{Optional: true, MarkdownDescription: "The lowest resolution, in milliseconds, to use when computing the chart's SignalFlow program. 0 lets Splunk Observability Cloud choose automatically."},
		"program":                    schema.StringAttribute{Optional: true, MarkdownDescription: "The SignalFlow program that produces the chart's data. Multiple statements are separated by semicolons or newlines. Required when this chart block is configured.", Validators: []validator.String{stringvalidator.LengthAtLeast(1)}},
		"sample_size":                schema.Int64Attribute{Optional: true, MarkdownDescription: "The maximum number of time series to sample when a query matches more than this many."},
		"show_timestamp":             schema.BoolAttribute{Optional: true, MarkdownDescription: "Whether to show the latest data point's timestamp in the chart footer. Defaults to `true` when unset."},
		"time_range":                 schema.StringAttribute{Optional: true, MarkdownDescription: "A relative time range override for this chart, such as \"15m\" or \"1h\", independent of the dashboard's own time range. Absolute ranges are not supported here.", Validators: []validator.String{stringvalidator.RegexMatches(regexp.MustCompile("^[1-9][0-9]*[smhdw]$"), "must be a positive whole-number duration such as 15m or 1h")}, PlanModifiers: []planmodifier.String{RelativeDurationSemanticEqualityModifier{}}},
		"title":                      schema.StringAttribute{Optional: true, MarkdownDescription: "The chart's display title, shown above the chart content."},
	}
}

func (p MetricsClusterMapModel) MissingRequiredFields() []string {
	var missing []string
	if p.ColorRange != nil {
		missing = append(missing, p.ColorRange.missingRequiredFields("color_range")...)
	}
	for i, item := range p.ColorScale {
		missing = append(missing, item.missingRequiredFields(fmt.Sprintf("color_scale.%d", i))...)
	}
	if p.DisplayUnit != nil {
		missing = append(missing, p.DisplayUnit.missingRequiredFields("display_unit")...)
	}
	if p.Program.IsNull() {
		missing = append(missing, "program")
	}
	return missing
}

func (p MetricsClusterMapModel) ValidationErrors() []ValidationError { return p.validationErrors("") }

func (p MetricsClusterMapModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "color_by"), p.ColorBy, false, 0, []string{"Range", "Scale"}...)...)
	if p.ColorRange != nil {
		validationErrors = append(validationErrors, p.ColorRange.validationErrors(validationPath(prefix, "color_range"))...)
	}
	if p.ColorScale != nil && len(p.ColorScale) > 5 {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "color_scale"), Message: "must contain at most 5 item(s)"})
	}
	for index, item := range p.ColorScale {
		validationErrors = append(validationErrors, item.validationErrors(fmt.Sprintf("%s.%d", validationPath(prefix, "color_scale"), index))...)
	}
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "description"), p.Description, false, 0, []string(nil)...)...)
	if p.DisplayUnit != nil {
		validationErrors = append(validationErrors, p.DisplayUnit.validationErrors(validationPath(prefix, "display_unit"))...)
	}
	if p.GroupBy != nil && len(p.GroupBy) > 2 {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "group_by"), Message: "must contain at most 2 item(s)"})
	}
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "max_delay"), p.MaxDelay, nil, nil)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "maximum_significant_digits"), p.MaximumSignificantDigits, int64Pointer(1), int64Pointer(20))...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "minimum_resolution"), p.MinimumResolution, nil, nil)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "program"), p.Program, true, 1, []string(nil)...)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "sample_size"), p.SampleSize, nil, nil)...)
	validationErrors = append(validationErrors, validateBool(validationPath(prefix, "show_timestamp"), p.ShowTimestamp, false)...)
	validationErrors = append(validationErrors, validateRelativeDuration(validationPath(prefix, "time_range"), p.TimeRange)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "title"), p.Title, false, 0, []string(nil)...)...)
	if p.ColorRange != nil && p.ColorScale != nil {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "color_range"), Message: "conflicts with color_scale"})
	}
	if p.ColorScale != nil && !(!p.ColorBy.IsNull() && !p.ColorBy.IsUnknown() && p.ColorBy.ValueString() == "Scale") {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "color_scale"), Message: "requires color_by to be \"Scale\""})
	}
	if !p.ColorBy.IsNull() && !p.ColorBy.IsUnknown() && p.ColorBy.ValueString() == "Scale" && !(p.ColorScale != nil && len(p.ColorScale) > 0) {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "color_scale"), Message: "must be non-empty when color_by is \"Scale\""})
	}
	return validationErrors
}

func (p MetricsClusterMapModel) BuildSpec() map[string]any {
	out := map[string]any{
		"<o11y:ClusterMap>": []any{},
		"chart":             map[string]any{},
		"datasource":        map[string]any{},
		"widget":            map[string]any{},
	}
	if !p.ColorBy.IsNull() && !p.ColorBy.IsUnknown() {
		setPath(out, []string{"chart", "colorBy"}, p.ColorBy.ValueString())
	}
	if p.ColorRange != nil {
		setPath(out, []string{"chart", "colorRange"}, p.ColorRange.buildSpec())
	}
	if p.ColorScale != nil {
		values := make([]any, len(p.ColorScale))
		for i, value := range p.ColorScale {
			values[i] = value.buildSpec()
		}
		setPath(out, []string{"chart", "colorScale"}, values)
	}
	if !p.Description.IsNull() && !p.Description.IsUnknown() {
		setPath(out, []string{"widget", "description"}, p.Description.ValueString())
	}
	if p.DisplayUnit != nil {
		setPath(out, []string{"chart", "displayUnit"}, p.DisplayUnit.buildSpec())
	}
	if p.GroupBy != nil {
		values := make([]any, len(p.GroupBy))
		for i, value := range p.GroupBy {
			values[i] = value.ValueString()
		}
		setPath(out, []string{"chart", "groupBy"}, values)
	}
	if !p.MaxDelay.IsNull() && !p.MaxDelay.IsUnknown() {
		setPath(out, []string{"datasource", "maxDelay"}, p.MaxDelay.ValueInt64())
	}
	if !p.MaximumSignificantDigits.IsNull() && !p.MaximumSignificantDigits.IsUnknown() {
		setPath(out, []string{"chart", "maximumSignificantDigits"}, p.MaximumSignificantDigits.ValueInt64())
	}
	if !p.MinimumResolution.IsNull() && !p.MinimumResolution.IsUnknown() {
		setPath(out, []string{"datasource", "minimumResolution"}, p.MinimumResolution.ValueInt64())
	}
	if !p.Program.IsNull() && !p.Program.IsUnknown() {
		setPath(out, []string{"datasource", "program"}, p.Program.ValueString())
	}
	if !p.SampleSize.IsNull() && !p.SampleSize.IsUnknown() {
		setPath(out, []string{"datasource", "sampleSize"}, p.SampleSize.ValueInt64())
	}
	if !p.ShowTimestamp.IsNull() && !p.ShowTimestamp.IsUnknown() {
		setPath(out, []string{"chart", "showTimestamp"}, p.ShowTimestamp.ValueBool())
	}
	if !p.TimeRange.IsNull() && !p.TimeRange.IsUnknown() {
		if duration, ok := RelativeDurationSpec(p.TimeRange.ValueString()); ok {
			setPath(out, []string{"datasource", "time"}, duration)
		}
	}
	if !p.Title.IsNull() && !p.Title.IsUnknown() {
		setPath(out, []string{"widget", "title"}, p.Title.ValueString())
	}
	return out
}

// ParseMetricsClusterMapSpec fills a MetricsClusterMapModel from a stored Dashify spec node,
// removing every value it claims. A path the document doesn't carry stays
// null, so an unset optional field round-trips as unset.
func ParseMetricsClusterMapSpec(spec map[string]any) (MetricsClusterMapModel, error) {
	TakeElement(spec, "<o11y:ClusterMap>")

	var model MetricsClusterMapModel
	var err error
	if model.ColorBy, err = TakeString(spec, []string{"chart", "colorBy"}, Scalar); err != nil {
		return model, err
	}
	if model.ColorRange, err = TakeObject(spec, []string{"chart", "colorRange"}, parseMetricsClusterMapColorRangeModel); err != nil {
		return model, err
	}
	if model.ColorScale, err = TakeObjectList(spec, []string{"chart", "colorScale"}, parseMetricsClusterMapColorScaleModel); err != nil {
		return model, err
	}
	if model.Description, err = TakeString(spec, []string{"widget", "description"}, Scalar); err != nil {
		return model, err
	}
	if model.DisplayUnit, err = TakeObject(spec, []string{"chart", "displayUnit"}, parseMetricsClusterMapDisplayUnitModel); err != nil {
		return model, err
	}
	if model.GroupBy, err = TakeStringList(spec, []string{"chart", "groupBy"}); err != nil {
		return model, err
	}
	if model.MaxDelay, err = TakeInt64(spec, []string{"datasource", "maxDelay"}, Scalar); err != nil {
		return model, err
	}
	if model.MaximumSignificantDigits, err = TakeInt64(spec, []string{"chart", "maximumSignificantDigits"}, Scalar); err != nil {
		return model, err
	}
	if model.MinimumResolution, err = TakeInt64(spec, []string{"datasource", "minimumResolution"}, Scalar); err != nil {
		return model, err
	}
	if model.Program, err = TakeString(spec, []string{"datasource", "program"}, Scalar); err != nil {
		return model, err
	}
	if model.SampleSize, err = TakeInt64(spec, []string{"datasource", "sampleSize"}, Scalar); err != nil {
		return model, err
	}
	if model.ShowTimestamp, err = TakeBool(spec, []string{"chart", "showTimestamp"}, Scalar); err != nil {
		return model, err
	}
	if model.TimeRange, err = TakeRelativeDuration(spec, []string{"datasource", "time"}); err != nil {
		return model, err
	}
	if model.Title, err = TakeString(spec, []string{"widget", "title"}, Scalar); err != nil {
		return model, err
	}

	return model, nil
}
