// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/observability/chartgen from internal/framework/observability/charts/schemas/metrics_single_value.yml; DO NOT EDIT.

package charts

import (
	"fmt"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

type MetricsSingleValueColorScaleModel struct {
	Gt           types.Float64 `tfsdk:"gt"`
	Gte          types.Float64 `tfsdk:"gte"`
	Lt           types.Float64 `tfsdk:"lt"`
	Lte          types.Float64 `tfsdk:"lte"`
	PaletteIndex types.Int64   `tfsdk:"palette_index"`
}

func (p MetricsSingleValueColorScaleModel) buildSpec() map[string]any {
	out := map[string]any{}
	if !p.Gt.IsNull() && !p.Gt.IsUnknown() {
		setPath(out, []string{"gt"}, p.Gt.ValueFloat64())
	}
	if !p.Gte.IsNull() && !p.Gte.IsUnknown() {
		setPath(out, []string{"gte"}, p.Gte.ValueFloat64())
	}
	if !p.Lt.IsNull() && !p.Lt.IsUnknown() {
		setPath(out, []string{"lt"}, p.Lt.ValueFloat64())
	}
	if !p.Lte.IsNull() && !p.Lte.IsUnknown() {
		setPath(out, []string{"lte"}, p.Lte.ValueFloat64())
	}
	if !p.PaletteIndex.IsNull() && !p.PaletteIndex.IsUnknown() {
		setPath(out, []string{"paletteIndex"}, p.PaletteIndex.ValueInt64())
	}
	return out
}

func parseMetricsSingleValueColorScaleModel(spec map[string]any) (MetricsSingleValueColorScaleModel, error) {
	var model MetricsSingleValueColorScaleModel
	var err error
	if model.Gt, err = TakeFloat64(spec, []string{"gt"}, Scalar); err != nil {
		return model, err
	}
	if model.Gte, err = TakeFloat64(spec, []string{"gte"}, Scalar); err != nil {
		return model, err
	}
	if model.Lt, err = TakeFloat64(spec, []string{"lt"}, Scalar); err != nil {
		return model, err
	}
	if model.Lte, err = TakeFloat64(spec, []string{"lte"}, Scalar); err != nil {
		return model, err
	}
	if model.PaletteIndex, err = TakeInt64(spec, []string{"paletteIndex"}, Scalar); err != nil {
		return model, err
	}
	return model, nil
}

func (p MetricsSingleValueColorScaleModel) missingRequiredFields(prefix string) []string {
	var missing []string
	return missing
}

func (p MetricsSingleValueColorScaleModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "gt"), p.Gt)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "gte"), p.Gte)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "lt"), p.Lt)...)
	validationErrors = append(validationErrors, validateFloat64(validationPath(prefix, "lte"), p.Lte)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "palette_index"), p.PaletteIndex, int64Pointer(0), int64Pointer(21))...)
	if !p.Gt.IsNull() && !p.Gt.IsUnknown() && !p.Gte.IsNull() && !p.Gte.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "gt"), Message: "conflicts with gte"})
	}
	if !p.Lt.IsNull() && !p.Lt.IsUnknown() && !p.Lte.IsNull() && !p.Lte.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "lt"), Message: "conflicts with lte"})
	}
	return validationErrors
}

type MetricsSingleValueDisplayUnitModel struct {
	Prefix types.String `tfsdk:"prefix"`
	Suffix types.String `tfsdk:"suffix"`
	Unit   types.String `tfsdk:"unit"`
}

func (p MetricsSingleValueDisplayUnitModel) buildSpec() any {
	if !p.Unit.IsNull() && !p.Unit.IsUnknown() {
		return p.Unit.ValueString()
	}
	obj := map[string]any{}
	if !p.Prefix.IsNull() && !p.Prefix.IsUnknown() {
		setPath(obj, []string{"prefix"}, p.Prefix.ValueString())
	}
	if !p.Suffix.IsNull() && !p.Suffix.IsUnknown() {
		setPath(obj, []string{"suffix"}, p.Suffix.ValueString())
	}
	if len(obj) == 0 {
		return nil
	}
	return obj
}

func parseMetricsSingleValueDisplayUnitModel(raw any) (MetricsSingleValueDisplayUnitModel, error) {
	var model MetricsSingleValueDisplayUnitModel
	var err error
	switch typed := raw.(type) {
	case string:
		model.Unit = types.StringValue(typed)
	case map[string]any:
		if model.Prefix, err = TakeString(typed, []string{"prefix"}, Scalar); err != nil {
			return model, err
		}
		if model.Suffix, err = TakeString(typed, []string{"suffix"}, Scalar); err != nil {
			return model, err
		}
	default:
		return model, fmt.Errorf("%T is not a valid value for this field", raw)
	}
	return model, nil
}

func (p MetricsSingleValueDisplayUnitModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "prefix"), p.Prefix, false, 0, []string(nil)...)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "suffix"), p.Suffix, false, 0, []string(nil)...)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "unit"), p.Unit, false, 0, []string{"Bit", "Kilobit", "Megabit", "Gigabit", "Terabit", "Petabit", "Exabit", "Zettabit", "Yottabit", "Byte", "Kibibyte", "Mebibyte", "Gibibyte", "Tebibyte", "Pebibyte", "Exbibyte", "Zebibyte", "Yobibyte", "Nanosecond", "Microsecond", "Millisecond", "Second", "Minute", "Hour", "Day", "Week"}...)...)
	if !p.Prefix.IsNull() && !p.Prefix.IsUnknown() && !p.Unit.IsNull() && !p.Unit.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "prefix"), Message: "conflicts with unit"})
	}
	if !p.Suffix.IsNull() && !p.Suffix.IsUnknown() && !p.Unit.IsNull() && !p.Unit.IsUnknown() {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "suffix"), Message: "conflicts with unit"})
	}
	if !(!p.Unit.IsNull() && !p.Unit.IsUnknown() && p.Unit.ValueString() != "" || !p.Prefix.IsNull() && !p.Prefix.IsUnknown() && p.Prefix.ValueString() != "" || !p.Suffix.IsNull() && !p.Suffix.IsUnknown() && p.Suffix.ValueString() != "") {
		validationErrors = append(validationErrors, ValidationError{Path: prefix, Message: "must set at least one of unit, prefix, suffix"})
	}
	return validationErrors
}

type MetricsSingleValueModel struct {
	ColorScale               []MetricsSingleValueColorScaleModel `tfsdk:"color_scale"`
	Description              types.String                        `tfsdk:"description"`
	DisplayUnit              *MetricsSingleValueDisplayUnitModel `tfsdk:"display_unit"`
	MaxDelay                 types.Int64                         `tfsdk:"max_delay"`
	MaximumFractionDigits    types.Int64                         `tfsdk:"maximum_fraction_digits"`
	MaximumSignificantDigits types.Int64                         `tfsdk:"maximum_significant_digits"`
	MinimumResolution        types.Int64                         `tfsdk:"minimum_resolution"`
	Program                  types.String                        `tfsdk:"program"`
	SampleSize               types.Int64                         `tfsdk:"sample_size"`
	SecondaryVisualization   types.String                        `tfsdk:"secondary_visualization"`
	ShowTimestamp            types.Bool                          `tfsdk:"show_timestamp"`
	TimeRange                types.String                        `tfsdk:"time_range"`
	Title                    types.String                        `tfsdk:"title"`
}

func MetricsSingleValueSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"color_scale":                schema.ListNestedAttribute{Optional: true, MarkdownDescription: "Color bands applied to the displayed value based on which threshold range it falls in. Buckets are evaluated in the order given.", NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{"gt": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's lower bound, exclusive. Mutually exclusive with `gte`."}, "gte": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's lower bound, inclusive. Mutually exclusive with `gt`."}, "lt": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's upper bound, exclusive. Mutually exclusive with `lte`. Not settable in the Dashify editor."}, "lte": schema.Float64Attribute{Optional: true, MarkdownDescription: "This bucket's upper bound, inclusive. Mutually exclusive with `lt`. Not settable in the Dashify editor."}, "palette_index": schema.Int64Attribute{Optional: true, MarkdownDescription: "The palette color index (0-21) to draw this bucket in.", Validators: []validator.Int64{int64validator.AtLeast(0), int64validator.AtMost(21)}}}}, Validators: []validator.List{listvalidator.SizeAtMost(5)}},
		"description":                schema.StringAttribute{Optional: true, MarkdownDescription: "Extended text shown below the title describing the chart's purpose."},
		"display_unit":               schema.SingleNestedAttribute{Optional: true, MarkdownDescription: "How to scale and label displayed values: either a named unit (bits, bytes, or a time duration) or a custom prefix/suffix pair. Omit for no unit conversion or annotation.", Attributes: map[string]schema.Attribute{"prefix": schema.StringAttribute{Optional: true, MarkdownDescription: "Text shown immediately before each displayed value.", Validators: []validator.String{stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("unit"))}}, "suffix": schema.StringAttribute{Optional: true, MarkdownDescription: "Text shown immediately after each displayed value.", Validators: []validator.String{stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("unit"))}}, "unit": schema.StringAttribute{Optional: true, MarkdownDescription: "A named unit Splunk Observability Cloud scales the raw value by (e.g. 1000 bytes displays as \"1 Kilobyte\" when the unit is Byte).", Validators: []validator.String{stringvalidator.OneOf("Bit", "Kilobit", "Megabit", "Gigabit", "Terabit", "Petabit", "Exabit", "Zettabit", "Yottabit", "Byte", "Kibibyte", "Mebibyte", "Gibibyte", "Tebibyte", "Pebibyte", "Exbibyte", "Zebibyte", "Yobibyte", "Nanosecond", "Microsecond", "Millisecond", "Second", "Minute", "Hour", "Day", "Week"), stringvalidator.ConflictsWith(path.MatchRelative().AtParent().AtName("prefix"), path.MatchRelative().AtParent().AtName("suffix"))}}}},
		"max_delay":                  schema.Int64Attribute{Optional: true, MarkdownDescription: "Milliseconds to wait for late-arriving data points before charting what has arrived. 0 lets Splunk Observability Cloud choose automatically."},
		"maximum_fraction_digits":    schema.Int64Attribute{Optional: true, MarkdownDescription: "The maximum number of digits to display after the decimal point.", Validators: []validator.Int64{int64validator.AtLeast(0), int64validator.AtMost(20)}},
		"maximum_significant_digits": schema.Int64Attribute{Optional: true, MarkdownDescription: "The number of significant digits to display for values in this chart. Unset lets Splunk Observability Cloud adjust precision to fit the available space. Defaults to `4` when unset.", Validators: []validator.Int64{int64validator.AtLeast(1), int64validator.AtMost(20)}},
		"minimum_resolution":         schema.Int64Attribute{Optional: true, MarkdownDescription: "The lowest resolution, in milliseconds, to use when computing the chart's SignalFlow program. 0 lets Splunk Observability Cloud choose automatically."},
		"program":                    schema.StringAttribute{Optional: true, MarkdownDescription: "The SignalFlow program that produces the chart's data. Multiple statements are separated by semicolons or newlines. Required when this chart block is configured.", Validators: []validator.String{stringvalidator.LengthAtLeast(1)}},
		"sample_size":                schema.Int64Attribute{Optional: true, MarkdownDescription: "The maximum number of time series to sample when a query matches more than this many."},
		"secondary_visualization":    schema.StringAttribute{Optional: true, MarkdownDescription: "An additional visualization (a sparkline or a radial/linear gauge) shown alongside the chart's primary value. Defaults to `None` when unset.", Validators: []validator.String{stringvalidator.OneOf("Linear", "None", "Radial", "Sparkline")}},
		"show_timestamp":             schema.BoolAttribute{Optional: true, MarkdownDescription: "Whether to show the latest data point's timestamp in the chart footer. Defaults to `true` when unset."},
		"time_range":                 schema.StringAttribute{Optional: true, MarkdownDescription: "A relative time range override for this chart, such as \"15m\" or \"1h\", independent of the dashboard's own time range. Absolute ranges are not supported here.", Validators: []validator.String{stringvalidator.RegexMatches(regexp.MustCompile("^[1-9][0-9]*[smhdw]$"), "must be a positive whole-number duration such as 15m or 1h")}, PlanModifiers: []planmodifier.String{RelativeDurationSemanticEqualityModifier{}}},
		"title":                      schema.StringAttribute{Optional: true, MarkdownDescription: "The chart's display title, shown above the chart content."},
	}
}

func (p MetricsSingleValueModel) MissingRequiredFields() []string {
	var missing []string
	for i, item := range p.ColorScale {
		missing = append(missing, item.missingRequiredFields(fmt.Sprintf("color_scale.%d", i))...)
	}
	if p.Program.IsNull() {
		missing = append(missing, "program")
	}
	return missing
}

func (p MetricsSingleValueModel) ValidationErrors() []ValidationError { return p.validationErrors("") }

func (p MetricsSingleValueModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	if p.ColorScale != nil && len(p.ColorScale) > 5 {
		validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, "color_scale"), Message: "must contain at most 5 item(s)"})
	}
	for index, item := range p.ColorScale {
		validationErrors = append(validationErrors, item.validationErrors(fmt.Sprintf("%s.%d", validationPath(prefix, "color_scale"), index))...)
	}
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "description"), p.Description, false, 0, []string(nil)...)...)
	if p.DisplayUnit != nil {
		validationErrors = append(validationErrors, p.DisplayUnit.validationErrors(validationPath(prefix, "display_unit"))...)
	}
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "max_delay"), p.MaxDelay, nil, nil)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "maximum_fraction_digits"), p.MaximumFractionDigits, int64Pointer(0), int64Pointer(20))...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "maximum_significant_digits"), p.MaximumSignificantDigits, int64Pointer(1), int64Pointer(20))...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "minimum_resolution"), p.MinimumResolution, nil, nil)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "program"), p.Program, true, 1, []string(nil)...)...)
	validationErrors = append(validationErrors, validateInt64(validationPath(prefix, "sample_size"), p.SampleSize, nil, nil)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "secondary_visualization"), p.SecondaryVisualization, false, 0, []string{"Linear", "None", "Radial", "Sparkline"}...)...)
	validationErrors = append(validationErrors, validateBool(validationPath(prefix, "show_timestamp"), p.ShowTimestamp, false)...)
	validationErrors = append(validationErrors, validateRelativeDuration(validationPath(prefix, "time_range"), p.TimeRange)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "title"), p.Title, false, 0, []string(nil)...)...)
	return validationErrors
}

func (p MetricsSingleValueModel) BuildSpec() map[string]any {
	out := map[string]any{
		"<o11y:SingleValue>": []any{},
		"chart":              map[string]any{},
		"datasource":         map[string]any{},
		"widget":             map[string]any{},
	}
	if p.ColorScale != nil {
		values := make([]any, len(p.ColorScale))
		for i, value := range p.ColorScale {
			values[i] = value.buildSpec()
		}
		setPath(out, []string{"chart", "colorScale"}, values)
	}
	if !p.Description.IsNull() && !p.Description.IsUnknown() {
		setPath(out, []string{"widget", "description"}, p.Description.ValueString())
	}
	if p.DisplayUnit != nil {
		if value := p.DisplayUnit.buildSpec(); value != nil {
			setPath(out, []string{"chart", "displayUnit"}, value)
		}
	}
	if !p.MaxDelay.IsNull() && !p.MaxDelay.IsUnknown() {
		setPath(out, []string{"datasource", "maxDelay"}, p.MaxDelay.ValueInt64())
	}
	if !p.MaximumFractionDigits.IsNull() && !p.MaximumFractionDigits.IsUnknown() {
		setPath(out, []string{"chart", "maximumFractionDigits"}, p.MaximumFractionDigits.ValueInt64())
	}
	if !p.MaximumSignificantDigits.IsNull() && !p.MaximumSignificantDigits.IsUnknown() {
		setPath(out, []string{"chart", "maximumSignificantDigits"}, p.MaximumSignificantDigits.ValueInt64())
	}
	if !p.MinimumResolution.IsNull() && !p.MinimumResolution.IsUnknown() {
		setPath(out, []string{"datasource", "minimumResolution"}, p.MinimumResolution.ValueInt64())
	}
	if !p.Program.IsNull() && !p.Program.IsUnknown() {
		setPath(out, []string{"datasource", "program"}, p.Program.ValueString())
	}
	if !p.SampleSize.IsNull() && !p.SampleSize.IsUnknown() {
		setPath(out, []string{"datasource", "sampleSize"}, p.SampleSize.ValueInt64())
	}
	if !p.SecondaryVisualization.IsNull() && !p.SecondaryVisualization.IsUnknown() {
		setPath(out, []string{"chart", "secondaryVisualization"}, p.SecondaryVisualization.ValueString())
	}
	if !p.ShowTimestamp.IsNull() && !p.ShowTimestamp.IsUnknown() {
		setPath(out, []string{"chart", "showTimestamp"}, p.ShowTimestamp.ValueBool())
	}
	if !p.TimeRange.IsNull() && !p.TimeRange.IsUnknown() {
		if duration, ok := RelativeDurationSpec(p.TimeRange.ValueString()); ok {
			setPath(out, []string{"datasource", "time"}, duration)
		}
	}
	if !p.Title.IsNull() && !p.Title.IsUnknown() {
		setPath(out, []string{"widget", "title"}, p.Title.ValueString())
	}
	return out
}

// ParseMetricsSingleValueSpec fills a MetricsSingleValueModel from a stored Dashify spec node,
// removing every value it claims. A path the document doesn't carry stays
// null, so an unset optional field round-trips as unset.
func ParseMetricsSingleValueSpec(spec map[string]any) (MetricsSingleValueModel, error) {
	TakeElement(spec, "<o11y:SingleValue>")

	var model MetricsSingleValueModel
	var err error
	if model.ColorScale, err = TakeObjectList(spec, []string{"chart", "colorScale"}, parseMetricsSingleValueColorScaleModel); err != nil {
		return model, err
	}
	if model.Description, err = TakeString(spec, []string{"widget", "description"}, Scalar); err != nil {
		return model, err
	}
	if model.DisplayUnit, err = TakeOneOf(spec, []string{"chart", "displayUnit"}, parseMetricsSingleValueDisplayUnitModel); err != nil {
		return model, err
	}
	if model.MaxDelay, err = TakeInt64(spec, []string{"datasource", "maxDelay"}, Scalar); err != nil {
		return model, err
	}
	if model.MaximumFractionDigits, err = TakeInt64(spec, []string{"chart", "maximumFractionDigits"}, Scalar); err != nil {
		return model, err
	}
	if model.MaximumSignificantDigits, err = TakeInt64(spec, []string{"chart", "maximumSignificantDigits"}, Scalar); err != nil {
		return model, err
	}
	if model.MinimumResolution, err = TakeInt64(spec, []string{"datasource", "minimumResolution"}, Scalar); err != nil {
		return model, err
	}
	if model.Program, err = TakeString(spec, []string{"datasource", "program"}, Scalar); err != nil {
		return model, err
	}
	if model.SampleSize, err = TakeInt64(spec, []string{"datasource", "sampleSize"}, Scalar); err != nil {
		return model, err
	}
	if model.SecondaryVisualization, err = TakeString(spec, []string{"chart", "secondaryVisualization"}, Scalar); err != nil {
		return model, err
	}
	if model.ShowTimestamp, err = TakeBool(spec, []string{"chart", "showTimestamp"}, Scalar); err != nil {
		return model, err
	}
	if model.TimeRange, err = TakeRelativeDuration(spec, []string{"datasource", "time"}); err != nil {
		return model, err
	}
	if model.Title, err = TakeString(spec, []string{"widget", "title"}, Scalar); err != nil {
		return model, err
	}

	return model, nil
}
