// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// Code generated by internal/framework/observability/chartgen from internal/framework/observability/charts/schemas/text.yml; DO NOT EDIT.

package charts

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TextModel struct {
	Description types.String `tfsdk:"description"`
	Markdown    types.String `tfsdk:"markdown"`
	Title       types.String `tfsdk:"title"`
}

func TextSchemaAttributes() map[string]schema.Attribute {
	return map[string]schema.Attribute{
		"description": schema.StringAttribute{Optional: true, MarkdownDescription: "Extended text shown below the title describing the chart's purpose."},
		"markdown":    schema.StringAttribute{Optional: true, MarkdownDescription: "The widget's body content, in GitHub-flavored Markdown or HTML."},
		"title":       schema.StringAttribute{Optional: true, MarkdownDescription: "The chart's display title, shown above the chart content."},
	}
}

func (p TextModel) MissingRequiredFields() []string {
	var missing []string
	return missing
}

func (p TextModel) ValidationErrors() []ValidationError { return p.validationErrors("") }

func (p TextModel) validationErrors(prefix string) []ValidationError {
	var validationErrors []ValidationError
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "description"), p.Description, false, 0, []string(nil)...)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "markdown"), p.Markdown, false, 0, []string(nil)...)...)
	validationErrors = append(validationErrors, validateString(validationPath(prefix, "title"), p.Title, false, 0, []string(nil)...)...)
	return validationErrors
}

func (p TextModel) BuildSpec() map[string]any {
	out := map[string]any{
		"<o11y:Text>": []any{},
		"chart":       map[string]any{},
		"widget":      map[string]any{},
	}
	if !p.Description.IsNull() && !p.Description.IsUnknown() {
		setPath(out, []string{"widget", "description"}, p.Description.ValueString())
	}
	if !p.Markdown.IsNull() && !p.Markdown.IsUnknown() {
		setPath(out, []string{"chart", "markdown"}, p.Markdown.ValueString())
	}
	if !p.Title.IsNull() && !p.Title.IsUnknown() {
		setPath(out, []string{"widget", "title"}, p.Title.ValueString())
	}
	return out
}

// ParseTextSpec fills a TextModel from a stored Dashify spec node,
// removing every value it claims. A path the document doesn't carry stays
// null, so an unset optional field round-trips as unset.
func ParseTextSpec(spec map[string]any) (TextModel, error) {
	TakeElement(spec, "<o11y:Text>")

	var model TextModel
	var err error
	if model.Description, err = TakeString(spec, []string{"widget", "description"}, Scalar); err != nil {
		return model, err
	}
	if model.Markdown, err = TakeString(spec, []string{"chart", "markdown"}, Scalar); err != nil {
		return model, err
	}
	if model.Title, err = TakeString(spec, []string{"widget", "title"}, Scalar); err != nil {
		return model, err
	}

	return model, nil
}
