// Copyright Splunk, Inc.
// SPDX-License-Identifier: MPL-2.0

// The chart generator turns every charts/schemas/*.yml chart schema into
// compiling Go that lives in its own package
// (internal/framework/observability/charts), separate from the hand-written
// dashboard package that imports it: one file per chart, a stable content
// registry, and a generated dashboard transport bridge. runGeneration is the
// entrypoint used by both write and non-mutating check modes. This is what
// makes the "schema files are build-time, not
// runtime" property real - nothing in the provider parses YAML at
// `terraform plan` time; the generated output gets committed and compiled
// in.
//
// The supported DSL covers scalar and enum properties, reversible negate and
// relative-duration transforms, list/map/block/oneof nested attributes, and
// array wrapping. Any future shape outside that explicit set fails generation
// rather than silently dropping a constraint.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	supportSchemaVersion      = 1
	chartGeneratorPath        = "internal/framework/observability/chartgen"
	chartSchemasPath          = "internal/framework/observability/charts/schemas"
	generatedCodeMarker       = "Code generated by " + chartGeneratorPath
	legacyGeneratedCodeMarker = "Code generated by internal/chartgen"
)

// --- YAML shape -------------------------------------------------------
//
// Mirrors charts/schemas/*.yml directly.

type chartSchema struct {
	Type string `yaml:"type"`

	// Version must exactly match supportSchemaVersion on a chart root. The
	// generator rejects both missing/zero and future versions so it can never
	// silently interpret a newer DSL with older semantics.
	Version int `yaml:"version"`

	Description    string              `yaml:"description"`
	Dashify        dashifyElement      `yaml:"dashify"`
	Extends        []string            `yaml:"extends"`
	Properties     map[string]property `yaml:"properties"`
	Normalizations []normalization     `yaml:"normalizations"`
}

type normalization struct {
	Kind   string   `yaml:"kind"`
	Target []string `yaml:"target"`
	Source []string `yaml:"source"`
	Unit   []string `yaml:"unit"`
	Prefix []string `yaml:"prefix"`
	Suffix []string `yaml:"suffix"`
}

type valueCondition struct {
	Field string `yaml:"field"`
	Value string `yaml:"value"`
}

func (c *valueCondition) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("value condition must be a mapping, got YAML kind %d", node.Kind)
	}
	if _, err := mappingPresence(node, map[string]bool{"field": true, "value": true}, "valueCondition"); err != nil {
		return err
	}
	type plainCondition valueCondition
	var decoded plainCondition
	if err := node.Decode(&decoded); err != nil {
		return err
	}
	*c = valueCondition(decoded)
	return nil
}

type dashifyElement struct {
	Element dashifyElementDefinition `yaml:"element"`
}

type dashifyElementDefinition struct {
	Name string `yaml:"name"`
	// Args is the element tag's value in the serialized document - the
	// `[]any{}` that BuildSpec seeds. Only an explicitly authored empty list
	// is supported; omission must not silently mean the same thing.
	Args        []any `yaml:"args"`
	argsPresent bool  `yaml:"-"`
}

func (e *dashifyElementDefinition) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("dashify element must be a mapping, got YAML kind %d", node.Kind)
	}
	present, err := mappingPresence(node, map[string]bool{"name": true, "args": true}, "dashifyElementDefinition")
	if err != nil {
		return err
	}
	type plainElement dashifyElementDefinition
	var decoded plainElement
	if err := node.Decode(&decoded); err != nil {
		return err
	}
	*e = dashifyElementDefinition(decoded)
	e.argsPresent = present["args"]
	return nil
}

type property struct {
	Type string `yaml:"type"` // string | bool | number | float | enum | list | map | block | oneof

	// Description is required on every property (chartgen fails generation
	// otherwise, see requireDescriptions) and becomes the generated
	// attribute's MarkdownDescription. A property that reaches its final
	// shape only through `ref` inherits the referenced property's
	// description unless it sets its own, via the same overlay rule as any
	// other field.
	Description string `yaml:"description"`

	// Ref inherits another property's whole shape: "<file>#<propertyName>".
	// Keys set alongside the ref win over the inherited ones, so a nested use
	// can reuse a common/ shape while supplying its own mapping.path.
	// `extends` is the root-level equivalent; `ref` is what makes a shape
	// reusable at an arbitrary nesting depth.
	Ref string `yaml:"ref"`

	Optional bool     `yaml:"optional"`
	Required bool     `yaml:"required"`
	Values   []string `yaml:"values"` // enum

	// Default is the value Dashify itself falls back to when the field is
	// absent from the document. It is rendered into the attribute's
	// MarkdownDescription and deliberately NOT emitted as a
	// terraform-plugin-framework Default: a framework default would need
	// Computed: true and would make the provider write a field the
	// practitioner never set, which would break the byte-for-byte document
	// round-trip the fixture tests require.
	Default any `yaml:"default"`

	// Min and Max bound a `number` property; anywhere else they are a
	// generation error (see requireEnforceableBounds) rather than a constraint
	// that looks declared but isn't.
	Min           *int            `yaml:"min"`
	Max           *int            `yaml:"max"`
	MinLength     *int            `yaml:"min_length"`
	ConflictsWith []string        `yaml:"conflicts_with"`
	AtLeastOneOf  []string        `yaml:"at_least_one_of"`
	RequiresValue *valueCondition `yaml:"requires_value"`
	RequiredWhen  *valueCondition `yaml:"required_when"`

	Mapping    propertyMapping     `yaml:"mapping"`
	Item       *itemSchema         `yaml:"item"`       // list | map
	Properties map[string]property `yaml:"properties"` // block
	Variants   map[string]property `yaml:"variants"`   // oneof
	MinItems   *int                `yaml:"min_items"`
	MaxItems   *int                `yaml:"max_items"`

	// present records which YAML keys were explicitly authored. It is what
	// lets a ref overlay deliberately replace true with false, a non-empty
	// slice/map with an empty one, or a value with null. Go zero values alone
	// cannot distinguish those cases from an omitted key.
	present map[string]bool `yaml:"-"`
}

type propertyMapping struct {
	Path      []string        `yaml:"path"`
	Wrap      string          `yaml:"wrap"`
	Transform string          `yaml:"transform"` // reversible named transform, e.g. negate or relative_duration
	present   map[string]bool `yaml:"-"`
}

type itemSchema struct {
	Type       string              `yaml:"type"`
	Properties map[string]property `yaml:"properties"`
}

func (i *itemSchema) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("item must be a mapping, got YAML kind %d", node.Kind)
	}
	if _, err := mappingPresence(node, map[string]bool{"type": true, "properties": true}, "itemSchema"); err != nil {
		return err
	}
	type plainItem itemSchema
	var decoded plainItem
	if err := node.Decode(&decoded); err != nil {
		return err
	}
	*i = itemSchema(decoded)
	return nil
}

var propertyYAMLKeys = map[string]bool{
	"type": true, "description": true, "ref": true, "optional": true,
	"required": true, "values": true, "default": true, "min": true,
	"max": true, "min_length": true, "conflicts_with": true,
	"at_least_one_of": true, "requires_value": true, "required_when": true,
	"mapping": true, "item": true, "properties": true, "variants": true,
	"min_items": true, "max_items": true,
}

func (p *property) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("property must be a mapping, got YAML kind %d", node.Kind)
	}
	present, err := mappingPresence(node, propertyYAMLKeys, "property")
	if err != nil {
		return err
	}
	type plainProperty property
	var decoded plainProperty
	if err := node.Decode(&decoded); err != nil {
		return err
	}
	*p = property(decoded)
	p.present = present
	return nil
}

func (m *propertyMapping) UnmarshalYAML(node *yaml.Node) error {
	if node.Kind != yaml.MappingNode {
		return fmt.Errorf("mapping must be a YAML mapping, got kind %d", node.Kind)
	}
	present, err := mappingPresence(node, map[string]bool{"path": true, "wrap": true, "transform": true}, "mapping")
	if err != nil {
		return err
	}
	type plainMapping propertyMapping
	var decoded plainMapping
	if err := node.Decode(&decoded); err != nil {
		return err
	}
	*m = propertyMapping(decoded)
	m.present = present
	return nil
}

func mappingPresence(node *yaml.Node, allowed map[string]bool, kind string) (map[string]bool, error) {
	present := make(map[string]bool, len(node.Content)/2)
	for index := 0; index < len(node.Content); index += 2 {
		key := node.Content[index].Value
		if !allowed[key] {
			return nil, fmt.Errorf("field %q not found in type main.%s", key, kind)
		}
		if present[key] {
			return nil, fmt.Errorf("duplicate %s key %q", kind, key)
		}
		present[key] = true
	}
	return present, nil
}

func (p property) has(key string) bool { return p.present[key] }

func (m propertyMapping) has(key string) bool { return m.present[key] }

// --- load + resolve extends ---------------------------------------------

// loadSchema reads path and recursively merges every `extends` entry's
// properties in first, so a chart-specific property of the same name always
// wins.
//
// Both `extends` and `ref` paths resolve against root (the charts/schemas
// directory), NOT against the referencing file's own directory - that
// matters for fragments inside common/, which refer to sibling common/ files
// the same way a chart schema does.
func loadSchema(root, path string) (*chartSchema, error) {
	loader, err := newSchemaLoader(root)
	if err != nil {
		return nil, err
	}
	// The entry chart path is supplied by the caller and is normally relative
	// to its working directory (for example ../charts/schemas/foo.yml).
	// Extends/ref paths, by contrast, are deliberately relative to the schema
	// root. Resolve only this initial path before handing it to the loader so
	// it cannot be joined to the root a second time.
	initial, err := filepath.Abs(path)
	if err != nil {
		return nil, err
	}
	return loader.load(initial)
}

type schemaLoader struct {
	root       string
	active     map[string]int
	activePath []string
}

func newSchemaLoader(root string) (*schemaLoader, error) {
	absolute, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("resolving schema root %s: %w", root, err)
	}
	canonical, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return nil, fmt.Errorf("resolving schema root %s: %w", root, err)
	}
	return &schemaLoader{root: canonical, active: map[string]int{}}, nil
}

func (l *schemaLoader) resolve(path string) (string, error) {
	if !filepath.IsAbs(path) {
		path = filepath.Join(l.root, path)
	}
	absolute, err := filepath.Abs(path)
	if err != nil {
		return "", err
	}
	canonical, err := filepath.EvalSymlinks(absolute)
	if err != nil {
		return "", err
	}
	relative, err := filepath.Rel(l.root, canonical)
	if err != nil {
		return "", err
	}
	if relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) || filepath.IsAbs(relative) {
		return "", fmt.Errorf("schema path %q escapes schema root %q", path, l.root)
	}
	return canonical, nil
}

func (l *schemaLoader) load(path string) (*chartSchema, error) {
	canonical, err := l.resolve(path)
	if err != nil {
		return nil, err
	}
	if first, ok := l.active[canonical]; ok {
		cycle := append(append([]string(nil), l.activePath[first:]...), canonical)
		for index := range cycle {
			if relative, relErr := filepath.Rel(l.root, cycle[index]); relErr == nil {
				cycle[index] = filepath.ToSlash(relative)
			}
		}
		return nil, fmt.Errorf("schema reference cycle: %s", strings.Join(cycle, " -> "))
	}
	l.active[canonical] = len(l.activePath)
	l.activePath = append(l.activePath, canonical)
	defer func() {
		delete(l.active, canonical)
		l.activePath = l.activePath[:len(l.activePath)-1]
	}()

	raw, err := os.ReadFile(canonical)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", canonical, err)
	}

	var s chartSchema
	if err := decodeStrictYAML(raw, &s); err != nil {
		return nil, fmt.Errorf("parsing %s: %w", canonical, err)
	}
	if s.Version != supportSchemaVersion {
		return nil, fmt.Errorf("%s: unsupported version %d (want exactly %d)", canonical, s.Version, supportSchemaVersion)
	}

	merged := map[string]property{}
	for _, ext := range s.Extends {
		extSchema, err := l.load(ext)
		if err != nil {
			return nil, fmt.Errorf("%s extends %q: %w", canonical, ext, err)
		}
		for name, p := range extSchema.Properties {
			merged[name] = p
		}
	}
	for name, p := range s.Properties {
		merged[name] = p
	}
	s.Properties = merged

	if err := l.resolveRefs(s.Properties); err != nil {
		return nil, err
	}

	if err := requireDescriptions(canonical, s.Properties, ""); err != nil {
		return nil, err
	}

	if err := requireEnforceableBounds(canonical, s.Properties, ""); err != nil {
		return nil, err
	}
	if err := requireSupportedDSL(canonical, s.Properties, ""); err != nil {
		return nil, err
	}
	if err := requireDistinctMappingPaths(canonical, s.Properties, ""); err != nil {
		return nil, err
	}

	return &s, nil
}

func requireSupportedDSL(schemaPath string, props map[string]property, prefix string) error {
	for _, name := range sortedKeys(props) {
		p := props[name]
		full := prefix + name
		if p.Optional && p.Required {
			return fmt.Errorf("%s: property %q cannot be both optional and required", schemaPath, full)
		}
		if !isSupportedPropertyType(p.Type) {
			return fmt.Errorf("%s: property %q has unsupported type %q", schemaPath, full, p.Type)
		}
		if p.Mapping.Wrap != "" && p.Mapping.Wrap != "array" {
			return fmt.Errorf("%s: property %q has unsupported mapping.wrap %q", schemaPath, full, p.Mapping.Wrap)
		}
		if p.Mapping.Wrap == "array" && !isScalarType(p.Type) {
			return fmt.Errorf("%s: property %q uses mapping.wrap array on non-scalar type %q", schemaPath, full, p.Type)
		}
		if p.Mapping.Wrap != "" && p.Mapping.Transform != "" {
			return fmt.Errorf("%s: property %q cannot combine mapping.wrap and mapping.transform", schemaPath, full)
		}
		switch p.Mapping.Transform {
		case "":
		case "negate":
			if p.Type != "bool" {
				return fmt.Errorf("%s: property %q uses negate on %q, want bool", schemaPath, full, p.Type)
			}
		case "relative_duration":
			if p.Type != "string" {
				return fmt.Errorf("%s: property %q uses relative_duration on %q, want string", schemaPath, full, p.Type)
			}
		default:
			return fmt.Errorf("%s: property %q has unsupported mapping.transform %q", schemaPath, full, p.Mapping.Transform)
		}
		for _, segment := range p.Mapping.Path {
			if segment == "" || segment == "*" {
				return fmt.Errorf("%s: property %q has invalid mapping.path segment %q", schemaPath, full, segment)
			}
		}
		if p.Type == "enum" {
			if len(p.Values) == 0 {
				return fmt.Errorf("%s: enum property %q has no values", schemaPath, full)
			}
			seen := map[string]bool{}
			for _, value := range p.Values {
				if value == "" || seen[value] {
					return fmt.Errorf("%s: enum property %q has empty or duplicate value %q", schemaPath, full, value)
				}
				seen[value] = true
			}
		}
		if err := rejectIrrelevantPropertyFields(schemaPath, full, p); err != nil {
			return err
		}
		if p.MinLength != nil && p.Type != "string" {
			return fmt.Errorf("%s: property %q uses min_length on %q, want string", schemaPath, full, p.Type)
		}
		if p.MinLength != nil && *p.MinLength < 0 {
			return fmt.Errorf("%s: property %q has negative min_length", schemaPath, full)
		}
		if (p.MinItems != nil || p.MaxItems != nil) && p.Type != "list" {
			return fmt.Errorf("%s: property %q uses item bounds on %q, want list", schemaPath, full, p.Type)
		}
		if p.MinItems != nil && (*p.MinItems < 0 || p.MaxItems != nil && *p.MinItems > *p.MaxItems) {
			return fmt.Errorf("%s: property %q has invalid item bounds", schemaPath, full)
		}
		if p.MaxItems != nil && *p.MaxItems < 0 {
			return fmt.Errorf("%s: property %q has negative max_items", schemaPath, full)
		}
		if p.Default != nil {
			if err := validatePropertyDefault(schemaPath, full, p); err != nil {
				return err
			}
		}
		if p.Type == "list" {
			if p.Item == nil || (p.Item.Type == "") == (len(p.Item.Properties) == 0) {
				return fmt.Errorf("%s: list property %q must have exactly one scalar item type or object properties", schemaPath, full)
			}
			if p.Item.Type != "" && p.Item.Type != "string" {
				return fmt.Errorf("%s: list property %q has unsupported scalar item type %q; DSL v1 generates only string scalar lists", schemaPath, full, p.Item.Type)
			}
		}
		if p.Type == "map" && (p.Item == nil || p.Item.Type != "" || len(p.Item.Properties) == 0) {
			return fmt.Errorf("%s: map property %q must have object item properties", schemaPath, full)
		}
		if p.Type == "block" && len(p.Properties) == 0 {
			return fmt.Errorf("%s: block property %q has no properties", schemaPath, full)
		}
		if p.Type == "oneof" && !isGeneratedOneof(p) {
			return fmt.Errorf("%s: oneof property %q has unsupported or ambiguous variants", schemaPath, full)
		}
		seenConflicts := map[string]bool{}
		for _, conflict := range p.ConflictsWith {
			if _, ok := props[conflict]; !ok || conflict == name {
				return fmt.Errorf("%s: property %q conflicts_with unknown/self field %q", schemaPath, full, conflict)
			}
			if seenConflicts[conflict] {
				return fmt.Errorf("%s: property %q has duplicate conflicts_with field %q", schemaPath, full, conflict)
			}
			seenConflicts[conflict] = true
			if !containsPropertyName(props[conflict].ConflictsWith, name) {
				return fmt.Errorf("%s: property %q conflicts_with %q is not reciprocal", schemaPath, full, conflict)
			}
		}
		for _, conditional := range []struct {
			name      string
			condition *valueCondition
		}{{"requires_value", p.RequiresValue}, {"required_when", p.RequiredWhen}} {
			conditionName, condition := conditional.name, conditional.condition
			if condition == nil {
				continue
			}
			target, ok := props[condition.Field]
			if !ok || (target.Type != "string" && target.Type != "enum") || condition.Value == "" {
				return fmt.Errorf("%s: property %q has invalid %s target/value", schemaPath, full, conditionName)
			}
			if target.Type == "enum" && !containsPropertyName(target.Values, condition.Value) {
				return fmt.Errorf("%s: property %q %s value %q is outside %q's enum", schemaPath, full, conditionName, condition.Value, condition.Field)
			}
		}

		children := nestedProperties(p)
		if len(p.AtLeastOneOf) > 0 {
			seenAtLeast := map[string]bool{}
			for _, field := range p.AtLeastOneOf {
				if _, ok := children[field]; !ok {
					return fmt.Errorf("%s: property %q at_least_one_of references unknown field %q", schemaPath, full, field)
				}
				if seenAtLeast[field] {
					return fmt.Errorf("%s: property %q has duplicate at_least_one_of field %q", schemaPath, full, field)
				}
				seenAtLeast[field] = true
			}
		}
		if p.Item != nil {
			if err := requireSupportedDSL(schemaPath, p.Item.Properties, full+".item."); err != nil {
				return err
			}
		}
		if err := requireSupportedDSL(schemaPath, p.Properties, full+"."); err != nil {
			return err
		}
		if err := requireSupportedDSL(schemaPath, p.Variants, full+"."); err != nil {
			return err
		}
	}
	return nil
}

func validatePropertyDefault(schemaPath, name string, prop property) error {
	invalid := func() error {
		return fmt.Errorf("%s: property %q default %#v is invalid for type %q", schemaPath, name, prop.Default, prop.Type)
	}
	switch prop.Type {
	case "string":
		value, ok := prop.Default.(string)
		if !ok || prop.MinLength != nil && len(value) < *prop.MinLength {
			return invalid()
		}
	case "enum":
		value, ok := prop.Default.(string)
		if !ok || !containsPropertyName(prop.Values, value) {
			return invalid()
		}
	case "bool":
		if _, ok := prop.Default.(bool); !ok {
			return invalid()
		}
	case "number":
		value, ok := defaultInt64(prop.Default)
		if !ok || prop.Min != nil && value < int64(*prop.Min) || prop.Max != nil && value > int64(*prop.Max) {
			return invalid()
		}
	case "float":
		if _, ok := defaultFloat64(prop.Default); !ok {
			return invalid()
		}
	default:
		return invalid()
	}
	return nil
}

func defaultInt64(value any) (int64, bool) {
	switch typed := value.(type) {
	case int:
		return int64(typed), true
	case int8:
		return int64(typed), true
	case int16:
		return int64(typed), true
	case int32:
		return int64(typed), true
	case int64:
		return typed, true
	default:
		return 0, false
	}
}

func defaultFloat64(value any) (float64, bool) {
	switch typed := value.(type) {
	case int:
		return float64(typed), true
	case int8:
		return float64(typed), true
	case int16:
		return float64(typed), true
	case int32:
		return float64(typed), true
	case int64:
		return float64(typed), true
	case float32:
		return float64(typed), true
	case float64:
		return typed, true
	default:
		return 0, false
	}
}

func containsPropertyName(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}
	return false
}

func rejectIrrelevantPropertyFields(schemaPath, name string, p property) error {
	allowed := map[string]bool{
		"type": true, "description": true, "ref": true, "optional": true,
		"required": true, "default": true, "conflicts_with": true,
		"requires_value": true, "required_when": true, "mapping": true,
	}
	switch p.Type {
	case "string":
		allowed["min_length"] = true
	case "enum":
		allowed["values"] = true
	case "number":
		allowed["min"], allowed["max"] = true, true
	case "list":
		allowed["item"], allowed["min_items"], allowed["max_items"] = true, true, true
	case "map":
		allowed["item"] = true
	case "block":
		allowed["properties"], allowed["at_least_one_of"] = true, true
	case "oneof":
		allowed["variants"], allowed["at_least_one_of"] = true, true
	}
	for key := range p.present {
		if !allowed[key] {
			return fmt.Errorf("%s: property %q sets %q, which is ignored for type %q", schemaPath, name, key, p.Type)
		}
	}
	return nil
}

func isSupportedPropertyType(propertyType string) bool {
	if isScalarType(propertyType) {
		return true
	}
	switch propertyType {
	case "list", "map", "block", "oneof":
		return true
	default:
		return false
	}
}

func requireDistinctMappingPaths(schemaPath string, props map[string]property, prefix string) error {
	type mappedProperty struct {
		name string
		path []string
	}
	var mapped []mappedProperty
	seenGoNames := map[string]string{}
	for _, name := range sortedKeys(props) {
		p := props[name]
		goName := exportedName(name)
		if prior, exists := seenGoNames[goName]; exists {
			return fmt.Errorf("%s: properties %q and %q collide as generated Go field %q", schemaPath, prefix+prior, prefix+name, goName)
		}
		seenGoNames[goName] = name
		if len(p.Mapping.Path) > 0 {
			for _, existing := range mapped {
				if pathHasPrefix(p.Mapping.Path, existing.path) || pathHasPrefix(existing.path, p.Mapping.Path) {
					return fmt.Errorf("%s: properties %q and %q have duplicate or prefix-colliding mapping paths %v and %v", schemaPath, prefix+existing.name, prefix+name, existing.path, p.Mapping.Path)
				}
			}
			mapped = append(mapped, mappedProperty{name: name, path: p.Mapping.Path})
		}
		if p.Item != nil {
			if err := requireDistinctMappingPaths(schemaPath, p.Item.Properties, prefix+name+".item."); err != nil {
				return err
			}
		}
		if err := requireDistinctMappingPaths(schemaPath, p.Properties, prefix+name+"."); err != nil {
			return err
		}
		for variantName, variant := range p.Variants {
			if variant.Type == "block" {
				if err := requireDistinctMappingPaths(schemaPath, variant.Properties, prefix+name+"."+variantName+"."); err != nil {
					return err
				}
			}
		}
	}
	return nil
}

func pathHasPrefix(path, prefix []string) bool {
	if len(prefix) > len(path) {
		return false
	}
	for index := range prefix {
		if path[index] != prefix[index] {
			return false
		}
	}
	return true
}

// requireEnforceableBounds rejects min/max on anything that isn't a `number`,
// where int64validator has nothing to bind them to. Without this a bound on a
// string or a list would parse cleanly and then vanish - the same class of
// silent no-op that KnownFields(true) exists to prevent, just one level deeper.
func requireEnforceableBounds(schemaPath string, props map[string]property, prefix string) error {
	for _, name := range sortedKeys(props) {
		p := props[name]
		full := prefix + name
		if (p.Min != nil || p.Max != nil) && p.Type != "number" {
			return fmt.Errorf("%s: property %q is type %q, but min/max are only enforceable on number", schemaPath, full, p.Type)
		}
		if p.Min != nil && p.Max != nil && *p.Min > *p.Max {
			return fmt.Errorf("%s: property %q has min %d greater than max %d", schemaPath, full, *p.Min, *p.Max)
		}
		if p.Item != nil {
			if err := requireEnforceableBounds(schemaPath, p.Item.Properties, full+".item."); err != nil {
				return err
			}
		}
		if err := requireEnforceableBounds(schemaPath, p.Properties, full+"."); err != nil {
			return err
		}
		if err := requireEnforceableBounds(schemaPath, p.Variants, full+"."); err != nil {
			return err
		}
	}

	return nil
}

// requireDescriptions fails loudly on any property with no description,
// including nested block/oneof/list-item/map-item properties, so a schema
// author cannot forget one - the same trap that already silently swallowed
// every default/min/max key before this existed. Runs after resolveRefs so a
// property that reaches its shape only through `ref` has already inherited
// its base's description.
func requireDescriptions(schemaPath string, props map[string]property, prefix string) error {
	for _, name := range sortedKeys(props) {
		p := props[name]
		full := prefix + name
		if p.Description == "" {
			return fmt.Errorf("%s: property %q has no description", schemaPath, full)
		}
		if p.Item != nil {
			if err := requireDescriptions(schemaPath, p.Item.Properties, full+".item."); err != nil {
				return err
			}
		}
		if err := requireDescriptions(schemaPath, p.Properties, full+"."); err != nil {
			return err
		}
		if err := requireDescriptions(schemaPath, p.Variants, full+"."); err != nil {
			return err
		}
	}

	return nil
}

// resolveRefs expands every `ref` in place, walking nested item/block/variant
// properties too - the list chart's ref sits three levels down, under
// published_streams.item.properties, not at the schema root.
func (l *schemaLoader) resolveRefs(props map[string]property) error {
	for name, p := range props {
		if p.Ref != "" {
			base, err := l.loadRef(p.Ref)
			if err != nil {
				return fmt.Errorf("resolving ref on %q: %w", name, err)
			}
			p = overlay(base, p)
			props[name] = p
		}

		if p.Item != nil {
			if err := l.resolveRefs(p.Item.Properties); err != nil {
				return err
			}
		}
		if err := l.resolveRefs(p.Properties); err != nil {
			return err
		}
		if err := l.resolveRefs(p.Variants); err != nil {
			return err
		}
	}

	return nil
}

// loadRef reads "<file>#<propertyName>", resolving file against root.
// loadSchema is reused rather than a bare yaml.Unmarshal so a referenced
// file's own extends/refs resolve first - refs can chain.
func (l *schemaLoader) loadRef(ref string) (property, error) {
	file, name, ok := strings.Cut(ref, "#")
	if !ok {
		return property{}, fmt.Errorf("malformed ref %q, want <file>#<propertyName>", ref)
	}

	if file == "" {
		return property{}, fmt.Errorf("malformed ref %q, file is empty", ref)
	}
	refSchema, err := l.load(file)
	if err != nil {
		return property{}, err
	}

	base, ok := refSchema.Properties[name]
	if !ok {
		return property{}, fmt.Errorf("ref %q: no property %q in %s", ref, name, file)
	}

	return base, nil
}

// overlay returns base with each explicitly authored local field taking
// precedence, including false, empty, and null values.
func overlay(base, local property) property {
	out := base
	if local.has("type") {
		out.Type = local.Type
	}
	if local.has("description") {
		out.Description = local.Description
	}
	if local.has("optional") {
		out.Optional = local.Optional
	}
	if local.has("required") {
		out.Required = local.Required
	}
	if local.has("values") {
		out.Values = local.Values
	}
	if local.has("default") {
		out.Default = local.Default
	}
	if local.has("min") {
		out.Min = local.Min
	}
	if local.has("max") {
		out.Max = local.Max
	}
	if local.has("min_length") {
		out.MinLength = local.MinLength
	}
	if local.has("conflicts_with") {
		out.ConflictsWith = local.ConflictsWith
	}
	if local.has("at_least_one_of") {
		out.AtLeastOneOf = local.AtLeastOneOf
	}
	if local.has("requires_value") {
		out.RequiresValue = local.RequiresValue
	}
	if local.has("required_when") {
		out.RequiredWhen = local.RequiredWhen
	}
	if local.has("mapping") {
		out.Mapping = overlayMapping(base.Mapping, local.Mapping)
	}
	if local.has("item") {
		out.Item = local.Item
	}
	if local.has("properties") {
		out.Properties = local.Properties
	}
	if local.has("variants") {
		out.Variants = local.Variants
	}
	if local.has("min_items") {
		out.MinItems = local.MinItems
	}
	if local.has("max_items") {
		out.MaxItems = local.MaxItems
	}
	out.Ref = ""
	out.present = mergePresence(base.present, local.present)

	return out
}

func overlayMapping(base, local propertyMapping) propertyMapping {
	out := base
	if local.has("path") {
		out.Path = local.Path
	}
	if local.has("wrap") {
		out.Wrap = local.Wrap
	}
	if local.has("transform") {
		out.Transform = local.Transform
	}
	out.present = mergePresence(base.present, local.present)
	return out
}

func mergePresence(base, local map[string]bool) map[string]bool {
	result := make(map[string]bool, len(base)+len(local))
	for key := range base {
		result[key] = true
	}
	for key := range local {
		result[key] = true
	}
	return result
}

// --- per-chart generation --------------------------------------------------

// isScalarType reports whether a property of this type can be represented as
// a single terraform-plugin-framework Attribute with no nested type of its
// own. list/map/block/oneof each need their own generation logic instead - a
// nested type plus a Block or Attribute, and a loop or switch in buildSpec -
// which the rest of this file provides for each.
func isScalarType(t string) bool {
	switch t {
	case "string", "bool", "number", "float", "enum":
		return true
	default:
		return false
	}
}

func supportedTransform(name string) bool {
	switch name {
	case "", "negate", "relative_duration":
		return true
	default:
		return false
	}
}

func isGeneratedProperty(p property) bool {
	if isScalarType(p.Type) {
		return supportedTransform(p.Mapping.Transform)
	}
	switch p.Type {
	case "block":
		return generatedObjectChildren(p.Properties)
	case "oneof":
		return isGeneratedOneof(p)
	case "list":
		if p.Item == nil {
			return false
		}
		if p.Item.Type != "" {
			return isScalarType(p.Item.Type)
		}
		return generatedObjectChildren(p.Item.Properties)
	case "map":
		return p.Item != nil && p.Item.Type == "" && generatedObjectChildren(p.Item.Properties)
	default:
		return false
	}
}

// isGeneratedOneof reports whether a oneof property's variants are all
// either a scalar (contributing one flattened field named after the variant)
// or a block of scalars (contributing one flattened field per child,
// flattened because HCL object-typed attributes can't hold a discriminated
// union - see flattenVariants), with no two scalar variants sharing the same
// serialized JSON type (string/enum both decode as a JSON string, so a oneof
// could not tell them apart on read) and no `required` anywhere inside,
// since required-ness inside a oneof isn't tracked by the generated code.
type oneofMappedField struct {
	name string
	path []string
}

func isGeneratedOneof(p property) bool {
	if len(p.Variants) == 0 {
		return false
	}
	seenKinds := map[string]bool{}
	seenFields := map[string]string{}
	seenGoFields := map[string]string{}
	var mapped []oneofMappedField
	for _, variantName := range sortedKeys(p.Variants) {
		v := p.Variants[variantName]
		if v.Required {
			return false
		}
		switch {
		case isScalarType(v.Type):
			if len(v.Mapping.Path) > 0 || v.Mapping.Wrap != "" || v.Mapping.Transform != "" {
				return false
			}
			kind := scalarSwitchKind(v.Type)
			if seenKinds[kind] {
				return false
			}
			seenKinds[kind] = true
			if !recordFlattenedOneofField(variantName, variantName, nil, seenFields, seenGoFields, &mapped) {
				return false
			}
		case v.Type == "block":
			if len(v.Mapping.Path) > 0 || v.Mapping.Wrap != "" || v.Mapping.Transform != "" {
				return false
			}
			for _, childName := range sortedKeys(v.Properties) {
				child := v.Properties[childName]
				if child.Required {
					return false
				}
				if !recordFlattenedOneofField(childName, variantName+"."+childName, child.Mapping.Path, seenFields, seenGoFields, &mapped) {
					return false
				}
			}
			if !generatedChildren(v.Properties) {
				return false
			}
		default:
			return false
		}
	}
	return true
}

func recordFlattenedOneofField(name, source string, path []string, seenNames, seenGoNames map[string]string, mapped *[]oneofMappedField) bool {
	if _, exists := seenNames[name]; exists {
		return false
	}
	seenNames[name] = source
	goName := exportedName(name)
	if _, exists := seenGoNames[goName]; exists {
		return false
	}
	seenGoNames[goName] = source
	if len(path) == 0 {
		return true
	}
	for _, prior := range *mapped {
		if pathHasPrefix(path, prior.path) || pathHasPrefix(prior.path, path) {
			return false
		}
	}
	*mapped = append(*mapped, oneofMappedField{source, path})
	return true
}

// scalarSwitchKind groups scalar YAML types by the Go type a decoded JSON
// value of that kind switches on - string and enum both arrive as a JSON
// string, so a oneof can't distinguish a string variant from an enum variant
// on read.
func scalarSwitchKind(t string) string {
	switch t {
	case "string", "enum":
		return "string"
	case "number", "float":
		// Both decode a JSON number and, worse, both would claim `case
		// float64:` in the generated parse switch - a oneof cannot have one
		// of each.
		return "number"
	default:
		return t
	}
}

// flattenVariants merges a oneof's variants into one flat field set: a
// scalar variant contributes one field named after the variant itself; a
// block variant contributes one field per child property. Both serialize to
// the oneof's own mapping.path directly - a bare scalar for the former, an
// object for the latter - never a nested "variant" wrapper, which is why a
// oneof needs its own generation logic rather than reusing block's.
func flattenVariants(variants map[string]property) map[string]property {
	out := map[string]property{}
	for _, name := range sortedKeys(variants) {
		v := variants[name]
		if v.Type == "block" {
			for childName, child := range v.Properties {
				out[childName] = child
			}
			continue
		}
		out[name] = v
	}
	return out
}

// variantConflicts maps each flattened field name to the sibling field names
// contributed by every *other* variant - the set a mutual-exclusivity
// validator must list on that field, since setting fields from two different
// variants at once is what a oneof forbids.
func variantConflicts(variants map[string]property) map[string][]string {
	groups := map[string][]string{}
	for _, vname := range sortedKeys(variants) {
		v := variants[vname]
		if v.Type == "block" {
			groups[vname] = append(groups[vname], sortedKeys(v.Properties)...)
		} else {
			groups[vname] = append(groups[vname], vname)
		}
	}

	groupNames := make([]string, 0, len(groups))
	for name := range groups {
		groupNames = append(groupNames, name)
	}
	sort.Strings(groupNames)

	out := map[string][]string{}
	for _, vname := range groupNames {
		var others []string
		for _, oname := range groupNames {
			if oname == vname {
				continue
			}
			others = append(others, groups[oname]...)
		}
		sort.Strings(others)
		for _, f := range groups[vname] {
			out[f] = others
		}
	}
	return out
}

// generatedChildren reports whether every child is a scalar with a
// supported transform and a mapping.path. This is the strict shape a
// oneof's block variant must have - writeOneofType only knows how to
// dispatch scalar children, so a variant with its own nested block/oneof
// isn't supported.
func generatedChildren(children map[string]property) bool {
	if len(children) == 0 {
		return false
	}
	for _, child := range children {
		if !isScalarType(child.Type) || !supportedTransform(child.Mapping.Transform) || len(child.Mapping.Path) == 0 {
			return false
		}
	}
	return true
}

// generatedObjectChildren reports whether every child - scalar, or itself a
// generatable block/oneof/list/map - has a mapping.path. This is the shape
// a block's own properties, or a list/map's object item, must have; unlike
// generatedChildren it allows nested complexity, which is what makes e.g.
// published_streams' map item (whose display_unit child is a oneof)
// generatable.
func generatedObjectChildren(children map[string]property) bool {
	if len(children) == 0 {
		return false
	}
	for _, child := range children {
		if !isGeneratedProperty(child) || len(child.Mapping.Path) == 0 {
			return false
		}
	}
	return true
}

// chartInfo is what generateChart hands back to runGeneration so it can wire
// the chart into the registry and dashboard bridge without re-parsing the schema.
type chartInfo struct {
	// Type is the YAML `type:` field - also the tfsdk block/attribute name
	// and the basis for the generated model/attributes/dispatch identifiers.
	Type string
	// ModelType is the generated struct's Go type name, e.g. "SingleValueModel".
	ModelType string
	// ElementTag is the dashify.element.name in its spec form, e.g.
	// "<o11y:SingleValue>". It's how the generated inverse dispatch recognizes
	// which chart type a stored spec node holds.
	ElementTag string
	// Description is the schema's top-level `description:`, used as the
	// chart's widget-content block MarkdownDescription.
	Description    string
	Normalizations []normalization
}

// generateChart reads schemaPath, resolves its extends/refs, and returns a
// complete, gofmt'd Go file in package packageName defining:
//   - a <Type>Model struct (exported, tfsdk-tagged) with one field per
//     supported scalar or nested property
//   - a <Type>SchemaAttributes() function returning the matching
//     map[string]schema.Attribute while preserving requiredness
//   - a (p <Type>Model) MissingRequiredFields() []string method
//   - a (p <Type>Model) BuildSpec() map[string]any method that seeds the map
//     with the chart's dashify.element.name tag and sets each field into it
//     via the shared setPath helper, following the property's mapping.path
//
// Everything here is exported since the generated charts package is imported
// by its parent observability package. Shared runtime helpers are hand-written
// once in charts/support.go.
func generateChart(schemaPath, packageName string) (src string, info chartInfo, err error) {
	root := filepath.Dir(schemaPath)
	s, err := loadSchema(root, schemaPath)
	if err != nil {
		return "", chartInfo{}, err
	}
	if s.Dashify.Element.Name == "" {
		return "", chartInfo{}, fmt.Errorf("%s: missing dashify.element.name", schemaPath)
	}
	if !s.Dashify.Element.argsPresent {
		return "", chartInfo{}, fmt.Errorf("%s: missing explicit dashify.element.args (want [])", schemaPath)
	}
	if len(s.Dashify.Element.Args) > 0 {
		return "", chartInfo{}, fmt.Errorf("%s: dashify.element.args has %d entries, but only the empty list is supported", schemaPath, len(s.Dashify.Element.Args))
	}
	if s.Description == "" {
		return "", chartInfo{}, fmt.Errorf("%s: missing top-level description", schemaPath)
	}
	if s.Version != supportSchemaVersion {
		return "", chartInfo{}, fmt.Errorf("%s: unsupported version %d (want exactly %d)", schemaPath, s.Version, supportSchemaVersion)
	}
	if validationErr := requireFinalPropertyPresence(schemaPath, s.Properties, ""); validationErr != nil {
		return "", chartInfo{}, validationErr
	}

	names := sortedKeys(s.Properties)
	var generatedNames []string
	for _, name := range names {
		p := s.Properties[name]
		switch {
		case !isGeneratedProperty(p):
			return "", chartInfo{}, fmt.Errorf("%s: property %q has unsupported type/shape/transform %q; every authored property must be generated", schemaPath, name, p.Type)
		case len(p.Mapping.Path) == 0:
			// Both serializers walk mapping.path, so an empty one would panic
			// at terraform plan time rather than here. Fail while the schema
			// author is still looking at it.
			return "", chartInfo{}, fmt.Errorf("%s: property %q has no mapping.path, so it cannot be serialized", schemaPath, name)
		default:
			generatedNames = append(generatedNames, name)
		}
	}

	typeName := exportedName(s.Type) + "Model"
	attrsFuncName := exportedName(s.Type) + "SchemaAttributes"

	var b strings.Builder
	b.WriteString("// Copyright Splunk, Inc.\n// SPDX-License-Identifier: MPL-2.0\n\n")
	fmt.Fprintf(&b, "// %s from %s/%s; DO NOT EDIT.\n", generatedCodeMarker, chartSchemasPath, filepath.Base(schemaPath))
	fmt.Fprintf(&b, "\npackage %s\n\n", packageName)

	elementTag := "<" + s.Dashify.Element.Name + ">"

	writeChartImports(&b, s.Properties, generatedNames)
	writeNestedTypes(&b, typeName, s.Properties, generatedNames)
	writeStruct(&b, typeName, s.Properties, generatedNames)
	writeSchemaAttributes(&b, attrsFuncName, typeName, s.Properties, generatedNames)
	writeMissingRequiredFields(&b, typeName, s.Properties, generatedNames)
	writeValidationErrors(&b, typeName, s.Properties, generatedNames, true, nil)
	writeBuildSpec(&b, typeName, elementTag, s.Properties, generatedNames)
	writeParseSpec(&b, exportedName(s.Type), typeName, elementTag, s.Properties, generatedNames)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", chartInfo{}, fmt.Errorf("generated Go for %s does not compile: %w\n\n%s", schemaPath, err, b.String())
	}

	return string(formatted), chartInfo{Type: s.Type, ModelType: typeName, ElementTag: elementTag, Description: s.Description, Normalizations: s.Normalizations}, nil
}

func requireFinalPropertyPresence(schemaPath string, properties map[string]property, prefix string) error {
	for _, name := range sortedKeys(properties) {
		prop := properties[name]
		logicalPath := prefix + name
		if prop.Optional == prop.Required {
			return fmt.Errorf("%s: property %q must set exactly one of optional or required", schemaPath, logicalPath)
		}
		if prop.Item != nil {
			if err := requireFinalPropertyPresence(schemaPath, prop.Item.Properties, logicalPath+".item."); err != nil {
				return err
			}
		}
		if err := requireFinalPropertyPresence(schemaPath, prop.Properties, logicalPath+"."); err != nil {
			return err
		}
		for _, variantName := range sortedKeys(prop.Variants) {
			variant := prop.Variants[variantName]
			if variant.Optional || variant.Required {
				return fmt.Errorf("%s: oneof variant %q must not declare optional or required; flattened variant fields are conditionally optional", schemaPath, logicalPath+"."+variantName)
			}
			if err := requireFinalPropertyPresence(schemaPath, variant.Properties, logicalPath+"."+variantName+"."); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeChartImports(b *strings.Builder, props map[string]property, names []string) {
	usesEnum := false
	usesComplex := false
	usesRelativeDuration := false
	usesListConstraints := false
	usesNumberBounds := false
	oneofKinds := map[string]bool{}
	for _, name := range names {
		p := props[name]
		if propertyUsesEnum(p) {
			usesEnum = true
		}
		if !isScalarType(p.Type) {
			usesComplex = true
		}
		if p.Mapping.Transform == "relative_duration" {
			usesRelativeDuration = true
		}
		if propertyUsesListConstraints(p) {
			usesListConstraints = true
		}
		if propertyUsesNumberBounds(p) {
			usesNumberBounds = true
		}
		collectOneofFieldKinds(p, oneofKinds)
	}
	usesOneof := len(oneofKinds) > 0
	needsStringValidator := usesEnum || usesRelativeDuration || oneofKinds["string"] || oneofKinds["enum"]
	needsBoolValidator := oneofKinds["bool"]
	needsInt64Validator := oneofKinds["number"] || usesNumberBounds
	needsFloat64Validator := oneofKinds["float"]

	b.WriteString("import (\n")
	if oneofKinds["number"] || oneofKinds["float"] {
		b.WriteString("\t\"encoding/json\"\n")
	}
	if usesComplex {
		b.WriteString("\t\"fmt\"\n")
	}
	if usesRelativeDuration {
		b.WriteString("\t\"regexp\"\n")
	}
	if usesComplex || usesRelativeDuration {
		b.WriteString("\n")
	}
	if usesOneof {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/path\"\n")
	}
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n")
	if usesRelativeDuration {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier\"\n")
	}
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n")
	if needsStringValidator || needsBoolValidator || needsInt64Validator || needsFloat64Validator || usesListConstraints {
		b.WriteString("\n")
		if needsBoolValidator {
			b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/boolvalidator\"\n")
		}
		if needsInt64Validator {
			b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/int64validator\"\n")
		}
		if needsFloat64Validator {
			b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/float64validator\"\n")
		}
		if usesListConstraints {
			b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator\"\n")
		}
		if needsStringValidator {
			b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator\"\n")
		}
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n")
	}
	b.WriteString(")\n\n")
}

// collectOneofFieldKinds walks p and every nested property (recursing the
// same way isGeneratedProperty's shapes do) recording the YAML type of every
// oneof-flattened field it finds, so writeChartImports can import exactly
// the validator packages those fields' ConflictsWith calls need.
func collectOneofFieldKinds(p property, kinds map[string]bool) {
	if p.Type == "oneof" {
		for _, child := range flattenVariants(p.Variants) {
			kinds[child.Type] = true
		}
	}
	for _, child := range nestedProperties(p) {
		collectOneofFieldKinds(child, kinds)
	}
}

func propertyUsesEnum(p property) bool {
	if p.Type == "enum" {
		return true
	}
	for _, child := range nestedProperties(p) {
		if child.Type == "enum" {
			return true
		}
	}
	return false
}

func propertyUsesListConstraints(p property) bool {
	if p.Type == "list" && (p.MinItems != nil || p.MaxItems != nil) {
		return true
	}
	for _, child := range nestedProperties(p) {
		if propertyUsesListConstraints(child) {
			return true
		}
	}
	return false
}

// propertyUsesNumberBounds reports whether p or anything nested under it needs
// int64validator for a min/max bound, so writeChartImports imports that
// package for a chart whose only use of it is a bounded number - not just for
// the oneof ConflictsWith case it used to cover.
func propertyUsesNumberBounds(p property) bool {
	if len(int64BoundsValidators(p)) > 0 {
		return true
	}
	for _, child := range nestedProperties(p) {
		if propertyUsesNumberBounds(child) {
			return true
		}
	}
	return false
}

func nestedProperties(p property) map[string]property {
	switch p.Type {
	case "block":
		return p.Properties
	case "oneof":
		return flattenVariants(p.Variants)
	}
	if p.Item != nil {
		return p.Item.Properties
	}
	return nil
}

// writeNestedTypes recursively emits every nested type reachable from
// props: for a oneof, its flattened struct (writeOneofType); for a block,
// or a list/map whose item is an object, that object's own nested types
// (recursing into its children first, so a grandchild type like
// published_streams' display_unit is always defined before the map-item
// type that embeds it) followed by the object type itself
// (writeObjectType). A scalar-item list/map, or a property with no nested
// shape at all, contributes nothing here.
func writeNestedTypes(b *strings.Builder, parentType string, props map[string]property, names []string) {
	for _, name := range names {
		p := props[name]
		typeName := nestedTypeName(parentType, name)

		switch p.Type {
		case "oneof":
			writeOneofType(b, typeName, p.Variants, p.AtLeastOneOf)
		case "block":
			writeNestedTypes(b, typeName, p.Properties, sortedKeys(p.Properties))
			writeObjectType(b, typeName, p.Properties, sortedKeys(p.Properties), p.AtLeastOneOf)
		case "list":
			if p.Item != nil && p.Item.Type == "" {
				writeNestedTypes(b, typeName, p.Item.Properties, sortedKeys(p.Item.Properties))
				writeObjectType(b, typeName, p.Item.Properties, sortedKeys(p.Item.Properties), nil)
			}
		case "map":
			if p.Item != nil {
				writeNestedTypes(b, typeName, p.Item.Properties, sortedKeys(p.Item.Properties))
				writeObjectType(b, typeName, p.Item.Properties, sortedKeys(p.Item.Properties), nil)
			}
		}
	}
}

// writeObjectType emits one <typeName> struct plus buildSpec/parse/
// missingRequiredFields methods for a flat set of children - the shape
// shared by a block's own properties, a list-of-objects' item properties,
// and a map-of-objects' item properties. Each child is written with the
// same per-type dispatch writeBuildSpec/writeParseSpec use at the chart
// root (writeFieldBuildStatement/writeFieldParseStatement), so a child
// that's itself a block/oneof/list/map works the same one level down as it
// does at the top - its own nested type was already emitted by the
// writeNestedTypes call that precedes this one.
func writeObjectType(b *strings.Builder, typeName string, children map[string]property, names, atLeastOneOf []string) {
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, name := range names {
		fmt.Fprintf(b, "\t%s %s `tfsdk:%q`\n", exportedName(name), goPropertyFieldType(typeName, name, children[name]), name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func (p %s) buildSpec() map[string]any {\n", typeName)
	b.WriteString("\tout := map[string]any{}\n")
	for _, name := range names {
		writeFieldBuildStatement(b, "p."+exportedName(name), children[name], "out")
	}
	b.WriteString("\treturn out\n}\n\n")

	fmt.Fprintf(b, "func parse%s(spec map[string]any) (%s, error) {\n", typeName, typeName)
	fmt.Fprintf(b, "\tvar model %s\n", typeName)
	b.WriteString("\tvar err error\n")
	for _, name := range names {
		writeFieldParseStatement(b, typeName, "model."+exportedName(name), name, children[name], "spec")
	}
	b.WriteString("\treturn model, nil\n}\n\n")

	fmt.Fprintf(b, "func (p %s) missingRequiredFields(prefix string) []string {\n", typeName)
	b.WriteString("\tvar missing []string\n")
	writeMissingRequiredFieldsBody(b, children, names, false)
	b.WriteString("\treturn missing\n}\n\n")
	writeValidationErrors(b, typeName, children, names, false, atLeastOneOf)
}

// writeFieldBuildStatement emits one property's contribution to a
// buildSpec method, dispatching on its type exactly as writeBuildSpec's
// per-chart loop always has - shared so a nested object's own buildSpec
// (see writeObjectType) supports the same shapes a chart root does.
func writeFieldBuildStatement(b *strings.Builder, accessor string, p property, root string) {
	if isScalarType(p.Type) {
		writeScalarBuild(b, accessor, p, root, "\t")
		return
	}
	path := goStringList(p.Mapping.Path)
	switch p.Type {
	case "block":
		fmt.Fprintf(b, "\tif %s != nil { setPath(%s, []string{%s}, %s.buildSpec()) }\n", accessor, root, path, accessor)
	case "oneof":
		fmt.Fprintf(b, "\tif %s != nil {\n\t\tif value := %s.buildSpec(); value != nil {\n\t\t\tsetPath(%s, []string{%s}, value)\n\t\t}\n\t}\n", accessor, accessor, root, path)
	case "list":
		if p.Item.Type != "" {
			fmt.Fprintf(b, "\tif %s != nil {\n\t\tvalues := make([]any, len(%s))\n\t\tfor i, value := range %s { values[i] = %s }\n\t\tsetPath(%s, []string{%s}, values)\n\t}\n", accessor, accessor, accessor, goValueExpr(p.Item.Type, "value"), root, path)
		} else {
			fmt.Fprintf(b, "\tif %s != nil {\n\t\tvalues := make([]any, len(%s))\n\t\tfor i, value := range %s { values[i] = value.buildSpec() }\n\t\tsetPath(%s, []string{%s}, values)\n\t}\n", accessor, accessor, accessor, root, path)
		}
	case "map":
		fmt.Fprintf(b, "\tif %s != nil {\n\t\tvalues := make(map[string]any, len(%s))\n\t\tfor key, value := range %s { values[key] = value.buildSpec() }\n\t\tsetPath(%s, []string{%s}, values)\n\t}\n", accessor, accessor, accessor, root, path)
	}
}

// writeFieldParseStatement emits one property's contribution to a parse
// function, the inverse of writeFieldBuildStatement. name and parentType
// are only used to derive the nested type's name (see nestedTypeName) for
// the block/oneof/list/map cases.
func writeFieldParseStatement(b *strings.Builder, parentType, field, name string, p property, root string) {
	if isScalarType(p.Type) {
		writeScalarParse(b, field, p, root, "\t")
		return
	}
	path := goStringList(p.Mapping.Path)
	nested := nestedTypeName(parentType, name)
	switch p.Type {
	case "block":
		fmt.Fprintf(b, "\tif %s, err = TakeObject(%s, []string{%s}, parse%s); err != nil { return model, err }\n", field, root, path, nested)
	case "oneof":
		fmt.Fprintf(b, "\tif %s, err = TakeOneOf(%s, []string{%s}, parse%s); err != nil { return model, err }\n", field, root, path, nested)
	case "list":
		if p.Item.Type == "string" || p.Item.Type == "enum" {
			fmt.Fprintf(b, "\tif %s, err = TakeStringList(%s, []string{%s}); err != nil { return model, err }\n", field, root, path)
		} else {
			fmt.Fprintf(b, "\tif %s, err = TakeObjectList(%s, []string{%s}, parse%s); err != nil { return model, err }\n", field, root, path, nested)
		}
	case "map":
		fmt.Fprintf(b, "\tif %s, err = TakeObjectMap(%s, []string{%s}, parse%s); err != nil { return model, err }\n", field, root, path, nested)
	}
}

// writeMissingRequiredFieldsBody emits the shared logic between a chart's
// exported MissingRequiredFields and a nested object type's
// missingRequiredFields(prefix): report every required scalar field that's
// null, then recurse into every block/list/map child (oneof children are
// never required - see isGeneratedOneof - so there is no such case here),
// each contributing its own missingRequiredFields under a name built from
// the running prefix. topLevel selects between a bare field name (the
// chart root has no incoming prefix) and prefix-relative ones.
func writeMissingRequiredFieldsBody(b *strings.Builder, props map[string]property, names []string, topLevel bool) {
	reportExpr := func(suffix string) string {
		if topLevel {
			return fmt.Sprintf("%q", suffix)
		}
		return fmt.Sprintf("prefix+%q", "."+suffix)
	}

	for _, name := range names {
		p := props[name]
		field := "p." + exportedName(name)
		switch {
		case isScalarType(p.Type):
			if p.Required {
				fmt.Fprintf(b, "\tif %s.IsNull() { missing = append(missing, %s) }\n", field, reportExpr(name))
			}
		case p.Type == "block":
			fmt.Fprintf(b, "\tif %s != nil { missing = append(missing, %s.missingRequiredFields(%s)...) }\n", field, field, reportExpr(name))
		case p.Type == "list" && p.Item != nil && p.Item.Type == "":
			fmt.Fprintf(b, "\tfor i, item := range %s { missing = append(missing, item.missingRequiredFields(fmt.Sprintf(%s, i))...) }\n", field, reportExpr(name+".%d"))
		case p.Type == "map":
			fmt.Fprintf(b, "\tfor key, item := range %s { missing = append(missing, item.missingRequiredFields(%s+key)...) }\n", field, reportExpr(name+"."))
		}
	}
}

// writeOneofType emits the nested struct for a oneof property: one field
// per flattened variant (see flattenVariants). Unlike a block, whose
// buildSpec always returns an object, a oneof's mapping.path holds one of
// two shapes depending which variant is active - a bare scalar for a
// scalar variant, an object for a block variant - so buildSpec returns `any`
// and picks whichever variant has a value set, and the inverse parse
// recovers the variant from the JSON shape it finds rather than from a
// discriminator field, since Dashify's document carries none.
func writeOneofType(b *strings.Builder, typeName string, variants map[string]property, atLeastOneOf []string) {
	flat := flattenVariants(variants)
	for name, conflicts := range variantConflicts(variants) {
		field := flat[name]
		field.ConflictsWith = append(field.ConflictsWith, conflicts...)
		flat[name] = field
	}
	hasBlockVariant := false
	for _, v := range variants {
		if v.Type == "block" {
			hasBlockVariant = true
		}
	}

	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, name := range sortedKeys(flat) {
		fmt.Fprintf(b, "\t%s %s `tfsdk:%q`\n", exportedName(name), goFieldType(flat[name]), name)
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "func (p %s) buildSpec() any {\n", typeName)
	for _, vname := range sortedKeys(variants) {
		v := variants[vname]
		if v.Type == "block" {
			continue
		}
		field := "p." + exportedName(vname)
		fmt.Fprintf(b, "\tif !%s.IsNull() && !%s.IsUnknown() {\n\t\treturn %s\n\t}\n", field, field, goValueExpr(v.Type, field))
	}
	if hasBlockVariant {
		b.WriteString("\tobj := map[string]any{}\n")
		for _, vname := range sortedKeys(variants) {
			v := variants[vname]
			if v.Type != "block" {
				continue
			}
			for _, childName := range sortedKeys(v.Properties) {
				writeScalarBuild(b, "p."+exportedName(childName), v.Properties[childName], "obj", "\t")
			}
		}
		b.WriteString("\tif len(obj) == 0 {\n\t\treturn nil\n\t}\n\treturn obj\n}\n\n")
	} else {
		b.WriteString("\treturn nil\n}\n\n")
	}

	fmt.Fprintf(b, "func parse%s(raw any) (%s, error) {\n", typeName, typeName)
	fmt.Fprintf(b, "\tvar model %s\n", typeName)
	if hasBlockVariant {
		b.WriteString("\tvar err error\n")
	}
	b.WriteString("\tswitch typed := raw.(type) {\n")
	for _, vname := range sortedKeys(variants) {
		v := variants[vname]
		if v.Type == "block" {
			continue
		}
		field := "model." + exportedName(vname)
		switch v.Type {
		case "string", "enum":
			fmt.Fprintf(b, "\tcase string:\n\t\t%s = types.StringValue(typed)\n", field)
		case "bool":
			fmt.Fprintf(b, "\tcase bool:\n\t\t%s = types.BoolValue(typed)\n", field)
		case "number":
			fmt.Fprintf(b, "\tcase int64, float64, json.Number:\n\t\tvalue, numberErr := jsonInt64(typed)\n\t\tif numberErr != nil { return model, numberErr }\n\t\t%s = types.Int64Value(value)\n", field)
		case "float":
			fmt.Fprintf(b, "\tcase int64, float64, json.Number:\n\t\tvalue, numberErr := jsonFloat64(typed)\n\t\tif numberErr != nil { return model, numberErr }\n\t\t%s = types.Float64Value(value)\n", field)
		}
	}
	if hasBlockVariant {
		b.WriteString("\tcase map[string]any:\n")
		for _, vname := range sortedKeys(variants) {
			v := variants[vname]
			if v.Type != "block" {
				continue
			}
			for _, childName := range sortedKeys(v.Properties) {
				writeScalarParse(b, "model."+exportedName(childName), v.Properties[childName], "typed", "\t\t")
			}
		}
	}
	b.WriteString("\tdefault:\n\t\treturn model, fmt.Errorf(\"%T is not a valid value for this field\", raw)\n")
	b.WriteString("\t}\n\treturn model, nil\n}\n\n")
	writeValidationErrors(b, typeName, flat, sortedKeys(flat), false, atLeastOneOf)
}

func nestedTypeName(parentType, propertyName string) string {
	return strings.TrimSuffix(parentType, "Model") + exportedName(propertyName) + "Model"
}

func writeStruct(b *strings.Builder, typeName string, props map[string]property, names []string) {
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	for _, name := range names {
		fmt.Fprintf(b, "\t%s %s `tfsdk:%q`\n", exportedName(name), goPropertyFieldType(typeName, name, props[name]), name)
	}
	b.WriteString("}\n\n")
}

func goPropertyFieldType(parentType, name string, p property) string {
	if isScalarType(p.Type) {
		return goFieldType(p)
	}
	nested := nestedTypeName(parentType, name)
	switch p.Type {
	case "block", "oneof":
		return "*" + nested
	case "list":
		if p.Item.Type != "" {
			return "[]" + goFieldType(property{Type: p.Item.Type})
		}
		return "[]" + nested
	case "map":
		return "map[string]" + nested
	default:
		panic("goPropertyFieldType called on unsupported property " + p.Type)
	}
}

func goFieldType(p property) string {
	switch p.Type {
	case "string", "enum":
		return "types.String"
	case "bool":
		return "types.Bool"
	case "number":
		return "types.Int64"
	case "float":
		return "types.Float64"
	default:
		panic("goFieldType called on non-scalar property type " + p.Type)
	}
}

func writeSchemaAttributes(b *strings.Builder, funcName, parentType string, props map[string]property, names []string) {
	fmt.Fprintf(b, "func %s() map[string]schema.Attribute {\n", funcName)
	b.WriteString("\treturn map[string]schema.Attribute{\n")
	for _, name := range names {
		p := props[name]
		fmt.Fprintf(b, "\t\t%q: ", name)
		writePropertySchema(b, parentType, name, p, true)
		b.WriteString(",\n")
	}
	b.WriteString("\t}\n}\n\n")
}

func writePropertySchema(b *strings.Builder, parentType, name string, p property, topLevel bool) {
	presence := "Optional: true"
	description := attributeDescription(p)
	// A required child directly inside an optional sibling chart block makes
	// Terraform Core require that child even when the whole sibling block is
	// absent. Keep root attributes optional in framework schema and enforce the
	// YAML required flag conditionally through generated model validation.
	// Required nested members are safe because their containing attribute is
	// already present when Core evaluates them.
	if p.Required && !topLevel {
		presence = "Required: true"
	}
	if p.Required && topLevel {
		if !strings.HasSuffix(description, ".") {
			description += "."
		}
		description += " Required when this chart block is configured."
	}
	switch p.Type {
	case "string":
		switch {
		case p.Mapping.Transform == "relative_duration":
			fmt.Fprintf(b, "schema.StringAttribute{%s, MarkdownDescription: %q, Validators: []validator.String{stringvalidator.RegexMatches(regexp.MustCompile(%q), %q)}, PlanModifiers: []planmodifier.String{RelativeDurationSemanticEqualityModifier{}}}", presence, description, `^[1-9][0-9]*[smhdw]$`, "must be a positive whole-number duration such as 15m or 1h")
		case p.MinLength != nil:
			fmt.Fprintf(b, "schema.StringAttribute{%s, MarkdownDescription: %q, Validators: []validator.String{stringvalidator.LengthAtLeast(%d)}}", presence, description, *p.MinLength)
		default:
			fmt.Fprintf(b, "schema.StringAttribute{%s, MarkdownDescription: %q}", presence, description)
		}
	case "bool":
		fmt.Fprintf(b, "schema.BoolAttribute{%s, MarkdownDescription: %q}", presence, description)
	case "number":
		if bounds := int64BoundsValidators(p); len(bounds) > 0 {
			fmt.Fprintf(b, "schema.Int64Attribute{%s, MarkdownDescription: %q, Validators: []validator.Int64{%s}}", presence, description, strings.Join(bounds, ", "))
		} else {
			fmt.Fprintf(b, "schema.Int64Attribute{%s, MarkdownDescription: %q}", presence, description)
		}
	case "float":
		fmt.Fprintf(b, "schema.Float64Attribute{%s, MarkdownDescription: %q}", presence, description)
	case "enum":
		fmt.Fprintf(b, "schema.StringAttribute{%s, MarkdownDescription: %q, Validators: []validator.String{stringvalidator.OneOf(%s)}}", presence, description, goStringList(p.Values))
	case "list":
		if p.Item.Type != "" {
			fmt.Fprintf(b, "schema.ListAttribute{%s, MarkdownDescription: %q, ElementType: %s", presence, description, terraformTypeExpr(p.Item.Type))
			writeListValidators(b, p)
			b.WriteString("}")
			return
		}
		fmt.Fprintf(b, "schema.ListNestedAttribute{%s, MarkdownDescription: %q, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{", presence, description)
		for _, childName := range sortedKeys(p.Item.Properties) {
			fmt.Fprintf(b, "%q: ", childName)
			writePropertySchema(b, nestedTypeName(parentType, name), childName, p.Item.Properties[childName], false)
			b.WriteString(",")
		}
		b.WriteString("}}")
		writeListValidators(b, p)
		b.WriteString("}")
	case "map":
		fmt.Fprintf(b, "schema.MapNestedAttribute{%s, MarkdownDescription: %q, NestedObject: schema.NestedAttributeObject{Attributes: map[string]schema.Attribute{", presence, description)
		for _, childName := range sortedKeys(p.Item.Properties) {
			fmt.Fprintf(b, "%q: ", childName)
			writePropertySchema(b, nestedTypeName(parentType, name), childName, p.Item.Properties[childName], false)
			b.WriteString(",")
		}
		b.WriteString("}}}")
	case "block":
		fmt.Fprintf(b, "schema.SingleNestedAttribute{%s, MarkdownDescription: %q, Attributes: map[string]schema.Attribute{", presence, description)
		for _, childName := range sortedKeys(p.Properties) {
			fmt.Fprintf(b, "%q: ", childName)
			writePropertySchema(b, nestedTypeName(parentType, name), childName, p.Properties[childName], false)
			b.WriteString(",")
		}
		b.WriteString("}}")
	case "oneof":
		fmt.Fprintf(b, "schema.SingleNestedAttribute{%s, MarkdownDescription: %q, Attributes: map[string]schema.Attribute{", presence, description)
		flat := flattenVariants(p.Variants)
		conflicts := variantConflicts(p.Variants)
		for _, childName := range sortedKeys(flat) {
			fmt.Fprintf(b, "%q: ", childName)
			writeOneofFieldSchema(b, flat[childName], conflicts[childName])
			b.WriteString(",")
		}
		b.WriteString("}}")
	}
}

// writeOneofFieldSchema writes one flattened oneof field's attribute
// literal: a plain scalar attribute plus a ConflictsWith validator listing
// every sibling field contributed by the *other* variants (see
// variantConflicts), so setting fields from two different variants at once
// - which the serialized document has no way to represent - is rejected at
// plan time instead of silently resolved by buildSpec's variant precedence.
func writeOneofFieldSchema(b *strings.Builder, p property, conflictsWith []string) {
	exprs := make([]string, len(conflictsWith))
	for i, name := range conflictsWith {
		exprs[i] = fmt.Sprintf("path.MatchRelative().AtParent().AtName(%q)", name)
	}
	conflictExpr := strings.Join(exprs, ", ")

	switch p.Type {
	case "string":
		fmt.Fprintf(b, "schema.StringAttribute{Optional: true, MarkdownDescription: %q, Validators: []validator.String{stringvalidator.ConflictsWith(%s)}}", attributeDescription(p), conflictExpr)
	case "enum":
		fmt.Fprintf(b, "schema.StringAttribute{Optional: true, MarkdownDescription: %q, Validators: []validator.String{stringvalidator.OneOf(%s), stringvalidator.ConflictsWith(%s)}}", attributeDescription(p), goStringList(p.Values), conflictExpr)
	case "bool":
		fmt.Fprintf(b, "schema.BoolAttribute{Optional: true, MarkdownDescription: %q, Validators: []validator.Bool{boolvalidator.ConflictsWith(%s)}}", attributeDescription(p), conflictExpr)
	case "number":
		validators := append(
			[]string{fmt.Sprintf("int64validator.ConflictsWith(%s)", conflictExpr)},
			int64BoundsValidators(p)...,
		)
		fmt.Fprintf(b, "schema.Int64Attribute{Optional: true, MarkdownDescription: %q, Validators: []validator.Int64{%s}}", attributeDescription(p), strings.Join(validators, ", "))
	case "float":
		fmt.Fprintf(b, "schema.Float64Attribute{Optional: true, MarkdownDescription: %q, Validators: []validator.Float64{float64validator.ConflictsWith(%s)}}", attributeDescription(p), conflictExpr)
	}
}

// attributeDescription is the MarkdownDescription every generated attribute
// gets: the schema's own description, plus a sentence naming Dashify's
// fallback when the schema records one. See property.Default for why a default
// is documented here instead of enforced as a framework Default.
func attributeDescription(p property) string {
	desc := strings.TrimSpace(p.Description)
	if p.Default == nil {
		return desc
	}
	if !strings.HasSuffix(desc, ".") {
		desc += "."
	}
	return fmt.Sprintf("%s Defaults to `%v` when unset.", desc, p.Default)
}

// int64BoundsValidators renders a number property's min/max as
// terraform-plugin-framework validator expressions, for callers to merge into
// whatever validator list the attribute already needs.
func int64BoundsValidators(p property) []string {
	var out []string
	if p.Min != nil {
		out = append(out, fmt.Sprintf("int64validator.AtLeast(%d)", *p.Min))
	}
	if p.Max != nil {
		out = append(out, fmt.Sprintf("int64validator.AtMost(%d)", *p.Max))
	}
	return out
}

func writeListValidators(b *strings.Builder, p property) {
	if p.MinItems == nil && p.MaxItems == nil {
		return
	}
	b.WriteString(", Validators: []validator.List{")
	if p.MinItems != nil {
		fmt.Fprintf(b, "listvalidator.SizeAtLeast(%d),", *p.MinItems)
	}
	if p.MaxItems != nil {
		fmt.Fprintf(b, "listvalidator.SizeAtMost(%d),", *p.MaxItems)
	}
	b.WriteString("}")
}

func terraformTypeExpr(propType string) string {
	switch propType {
	case "string", "enum":
		return "types.StringType"
	case "bool":
		return "types.BoolType"
	case "number":
		return "types.Int64Type"
	case "float":
		return "types.Float64Type"
	default:
		panic("terraformTypeExpr called on unsupported type " + propType)
	}
}

// writeMissingRequiredFields emits a method reporting which required (per
// the YAML) fields are unset. IsNull is used rather than a zero-value check
// (e.g. ValueString() == "") since a legitimate value can be the zero value
// (false, 0) - only IsNull distinguishes "unset" correctly for every scalar
// type this package generates.
func writeMissingRequiredFields(b *strings.Builder, typeName string, props map[string]property, names []string) {
	fmt.Fprintf(b, "func (p %s) MissingRequiredFields() []string {\n", typeName)
	b.WriteString("\tvar missing []string\n")
	writeMissingRequiredFieldsBody(b, props, names, true)
	b.WriteString("\treturn missing\n}\n\n")
}

// writeValidationErrors emits runtime validation used both for Terraform
// configuration diagnostics and for deciding whether imported JSON is safe to
// canonicalize into typed state. Terraform schema validators remain useful for
// immediate field diagnostics, but imports do not pass through configuration
// validation, so the generated model must enforce the same contract itself.
func writeValidationErrors(b *strings.Builder, typeName string, props map[string]property, names []string, exported bool, atLeastOneOf []string) {
	if exported {
		fmt.Fprintf(b, "func (p %s) ValidationErrors() []ValidationError { return p.validationErrors(\"\") }\n\n", typeName)
	}
	fmt.Fprintf(b, "func (p %s) validationErrors(prefix string) []ValidationError {\n", typeName)
	b.WriteString("\tvar validationErrors []ValidationError\n")

	for _, name := range names {
		p := props[name]
		field := "p." + exportedName(name)
		pathExpr := fmt.Sprintf("validationPath(prefix, %q)", name)
		switch p.Type {
		case "string", "enum":
			minLength := 0
			if p.MinLength != nil {
				minLength = *p.MinLength
			}
			if p.Mapping.Transform == "relative_duration" {
				if p.Required {
					fmt.Fprintf(b, "\tif !%s.IsUnknown() && %s.IsNull() { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, field, pathExpr)
				}
				fmt.Fprintf(b, "\tvalidationErrors = append(validationErrors, validateRelativeDuration(%s, %s)...)\n", pathExpr, field)
				continue
			}
			allowed := "[]string(nil)"
			if p.Type == "enum" {
				allowed = "[]string{" + goStringList(p.Values) + "}"
			}
			fmt.Fprintf(b, "\tvalidationErrors = append(validationErrors, validateString(%s, %s, %t, %d, %s...)...)\n", pathExpr, field, p.Required, minLength, allowed)
		case "bool":
			fmt.Fprintf(b, "\tvalidationErrors = append(validationErrors, validateBool(%s, %s, %t)...)\n", pathExpr, field, p.Required)
		case "number":
			if p.Required {
				fmt.Fprintf(b, "\tif !%s.IsUnknown() && %s.IsNull() { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, field, pathExpr)
			}
			fmt.Fprintf(b, "\tvalidationErrors = append(validationErrors, validateInt64(%s, %s, %s, %s)...)\n", pathExpr, field, int64PointerExpr(p.Min), int64PointerExpr(p.Max))
		case "float":
			if p.Required {
				fmt.Fprintf(b, "\tif !%s.IsUnknown() && %s.IsNull() { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, field, pathExpr)
			}
			fmt.Fprintf(b, "\tvalidationErrors = append(validationErrors, validateFloat64(%s, %s)...)\n", pathExpr, field)
		case "block", "oneof":
			if p.Required {
				fmt.Fprintf(b, "\tif %s == nil { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, pathExpr)
			}
			fmt.Fprintf(b, "\tif %s != nil { validationErrors = append(validationErrors, %s.validationErrors(%s)...) }\n", field, field, pathExpr)
		case "list":
			if p.Required {
				fmt.Fprintf(b, "\tif %s == nil { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, pathExpr)
			}
			if p.MinItems != nil {
				fmt.Fprintf(b, "\tif %s != nil && len(%s) < %d { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must contain at least %d item(s)\"}) }\n", field, field, *p.MinItems, pathExpr, *p.MinItems)
			}
			if p.MaxItems != nil {
				fmt.Fprintf(b, "\tif %s != nil && len(%s) > %d { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must contain at most %d item(s)\"}) }\n", field, field, *p.MaxItems, pathExpr, *p.MaxItems)
			}
			if p.Item != nil && p.Item.Type == "" {
				fmt.Fprintf(b, "\tfor index, item := range %s { validationErrors = append(validationErrors, item.validationErrors(fmt.Sprintf(\"%%s.%%d\", %s, index))...) }\n", field, pathExpr)
			}
		case "map":
			if p.Required {
				fmt.Fprintf(b, "\tif %s == nil { validationErrors = append(validationErrors, ValidationError{Path: %s, Message: \"must be set\"}) }\n", field, pathExpr)
			}
			fmt.Fprintf(b, "\tfor _, key := range sortedMapKeys(%s) { item := %s[key]; validationErrors = append(validationErrors, item.validationErrors(validationPath(%s, key))...) }\n", field, field, pathExpr)
		}
	}

	for _, name := range names {
		p := props[name]
		field := "p." + exportedName(name)
		for _, other := range p.ConflictsWith {
			otherProp, ok := props[other]
			if !ok || name >= other {
				continue
			}
			fmt.Fprintf(b, "\tif %s && %s { validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, %q), Message: %q}) }\n", configuredExpr(field, p), configuredExpr("p."+exportedName(other), otherProp), name, "conflicts with "+other)
		}
		if p.RequiresValue != nil {
			if target, ok := props[p.RequiresValue.Field]; ok {
				fmt.Fprintf(b, "\tif %s && !(%s) { validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, %q), Message: %q}) }\n", configuredExpr(field, p), equalsStringExpr("p."+exportedName(p.RequiresValue.Field), target, p.RequiresValue.Value), name, fmt.Sprintf("requires %s to be %q", p.RequiresValue.Field, p.RequiresValue.Value))
			}
		}
		if p.RequiredWhen != nil {
			if target, ok := props[p.RequiredWhen.Field]; ok {
				fmt.Fprintf(b, "\tif %s && !(%s) { validationErrors = append(validationErrors, ValidationError{Path: validationPath(prefix, %q), Message: %q}) }\n", equalsStringExpr("p."+exportedName(p.RequiredWhen.Field), target, p.RequiredWhen.Value), nonEmptyExpr(field, p), name, fmt.Sprintf("must be non-empty when %s is %q", p.RequiredWhen.Field, p.RequiredWhen.Value))
			}
		}
	}

	if len(atLeastOneOf) > 0 {
		var configured []string
		for _, name := range atLeastOneOf {
			if p, ok := props[name]; ok {
				configured = append(configured, nonEmptyExpr("p."+exportedName(name), p))
			}
		}
		if len(configured) > 0 {
			fmt.Fprintf(b, "\tif !(%s) { validationErrors = append(validationErrors, ValidationError{Path: prefix, Message: %q}) }\n", strings.Join(configured, " || "), "must set at least one of "+strings.Join(atLeastOneOf, ", "))
		}
	}

	b.WriteString("\treturn validationErrors\n}\n\n")
}

func int64PointerExpr(value *int) string {
	if value == nil {
		return "nil"
	}
	return fmt.Sprintf("int64Pointer(%d)", *value)
}

func configuredExpr(accessor string, p property) string {
	if isScalarType(p.Type) {
		return fmt.Sprintf("!%s.IsNull() && !%s.IsUnknown()", accessor, accessor)
	}
	return accessor + " != nil"
}

func nonEmptyExpr(accessor string, p property) string {
	if isScalarType(p.Type) {
		if p.Type == "string" || p.Type == "enum" {
			return fmt.Sprintf("!%s.IsNull() && !%s.IsUnknown() && %s.ValueString() != \"\"", accessor, accessor, accessor)
		}
		return configuredExpr(accessor, p)
	}
	switch p.Type {
	case "list", "map":
		return accessor + " != nil && len(" + accessor + ") > 0"
	default:
		return accessor + " != nil"
	}
}

func equalsStringExpr(accessor string, p property, value string) string {
	if p.Type != "string" && p.Type != "enum" {
		return "false"
	}
	return fmt.Sprintf("!%s.IsNull() && !%s.IsUnknown() && %s.ValueString() == %q", accessor, accessor, accessor, value)
}

// writeBuildSpec emits a method that seeds the Dashify containers referenced
// by this chart's properties and then, per configured property, a setPath
// call following its mapping.path. Null and unknown Terraform values are
// omitted so an absent optional field never becomes an empty string, false,
// or zero in the template. Deriving the containers matters for chart types
// such as o11y:Text, whose document contract has no datasource at all.
func writeBuildSpec(b *strings.Builder, typeName, elementTag string, props map[string]property, names []string) {
	fmt.Fprintf(b, "func (p %s) BuildSpec() map[string]any {\n", typeName)
	b.WriteString("\tout := map[string]any{\n")
	fmt.Fprintf(b, "\t\t%q: []any{},\n", elementTag)
	for _, root := range buildSpecRoots(props, names) {
		fmt.Fprintf(b, "\t\t%q: map[string]any{},\n", root)
	}
	b.WriteString("\t}\n")
	for _, name := range names {
		writeFieldBuildStatement(b, "p."+exportedName(name), props[name], "out")
	}
	b.WriteString("\treturn out\n}\n")
}

func buildSpecRoots(props map[string]property, names []string) []string {
	roots := map[string]bool{}
	for _, name := range names {
		if path := props[name].Mapping.Path; len(path) > 0 {
			roots[path[0]] = true
		}
	}
	out := make([]string, 0, len(roots))
	for root := range roots {
		out = append(out, root)
	}
	sort.Strings(out)
	return out
}

func writeScalarBuild(b *strings.Builder, accessor string, p property, root, indent string) {
	value := goValueExpr(p.Type, accessor)
	switch p.Mapping.Transform {
	case "negate":
		value = "!" + value
	case "relative_duration":
		path := goStringList(p.Mapping.Path)
		fmt.Fprintf(b, "%sif !%s.IsNull() && !%s.IsUnknown() {\n", indent, accessor, accessor)
		fmt.Fprintf(b, "%s\tif duration, ok := RelativeDurationSpec(%s); ok { setPath(%s, []string{%s}, duration) }\n", indent, value, root, path)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	default:
	}
	path := goStringList(p.Mapping.Path)
	fmt.Fprintf(b, "%sif !%s.IsNull() && !%s.IsUnknown() {\n", indent, accessor, accessor)
	if p.Mapping.Wrap == "array" {
		fmt.Fprintf(b, "%s\tsetPath(%s, []string{%s}, []any{%s})\n", indent, root, path, value)
	} else {
		fmt.Fprintf(b, "%s\tsetPath(%s, []string{%s}, %s)\n", indent, root, path, value)
	}
	fmt.Fprintf(b, "%s}\n", indent)
}

func goValueExpr(propType, accessor string) string {
	switch propType {
	case "string", "enum":
		return accessor + ".ValueString()"
	case "bool":
		return accessor + ".ValueBool()"
	case "number":
		return accessor + ".ValueInt64()"
	case "float":
		return accessor + ".ValueFloat64()"
	default:
		panic("goValueExpr called on non-scalar property type " + propType)
	}
}

// writeParseSpec emits the inverse of BuildSpec: one take* call per property,
// following the same mapping.path. The take* helpers remove what they read
// (see charts/support.go), so a caller can report whatever
// is left as content the typed schema does not model - which is the whole
// point of generating both directions from one mapping definition rather than
// hand-writing a reader that can silently drift from the writer.
func writeParseSpec(b *strings.Builder, typeBase, typeName, elementTag string, props map[string]property, names []string) {
	fmt.Fprintf(b, "\n// Parse%sSpec fills a %s from a stored Dashify spec node,\n", typeBase, typeName)
	b.WriteString("// removing every value it claims. A path the document doesn't carry stays\n")
	b.WriteString("// null, so an unset optional field round-trips as unset.\n")
	fmt.Fprintf(b, "func Parse%sSpec(spec map[string]any) (%s, error) {\n", typeBase, typeName)
	fmt.Fprintf(b, "\tTakeElement(spec, %q)\n\n", elementTag)
	fmt.Fprintf(b, "\tvar model %s\n", typeName)
	if len(names) == 0 {
		b.WriteString("\treturn model, nil\n}\n")
		return
	}

	b.WriteString("\tvar err error\n")
	for _, name := range names {
		writeFieldParseStatement(b, typeName, "model."+exportedName(name), name, props[name], "spec")
	}

	b.WriteString("\n\treturn model, nil\n}\n")
}

func writeScalarParse(b *strings.Builder, field string, p property, root, indent string) {
	path := goStringList(p.Mapping.Path)
	if p.Mapping.Transform == "relative_duration" {
		fmt.Fprintf(b, "%sif %s, err = TakeRelativeDuration(%s, []string{%s}); err != nil { return model, err }\n", indent, field, root, path)
		return
	}
	fmt.Fprintf(b, "%sif %s, err = %s(%s, []string{%s}, %s); err != nil { return model, err }\n", indent, field, goTakeFunc(p.Type), root, path, goValueShape(p.Mapping.Wrap))
	if p.Mapping.Transform == "negate" {
		fmt.Fprintf(b, "%sif !%s.IsNull() && !%s.IsUnknown() { %s = types.BoolValue(!%s.ValueBool()) }\n", indent, field, field, field, field)
	}
}

// goValueShape hands mapping.wrap to the parser so reading expects the same
// document form writing produces - see ValueShape in
// charts/support.go.
func goValueShape(wrap string) string {
	if wrap == "array" {
		return "WrappedInArray"
	}

	return "Scalar"
}

func goTakeFunc(propType string) string {
	switch propType {
	case "string", "enum":
		return "TakeString"
	case "bool":
		return "TakeBool"
	case "number":
		return "TakeInt64"
	case "float":
		return "TakeFloat64"
	default:
		panic("goTakeFunc called on non-scalar property type " + propType)
	}
}

// generateContentAggregate emits only the stable child-package registry. The
// dashboard transport structs live in a separately generated dashboard-package
// bridge to avoid an import cycle.
func generateContentAggregate(charts []chartInfo, packageName string) (string, error) {
	var b strings.Builder
	b.WriteString("// Copyright Splunk, Inc.\n// SPDX-License-Identifier: MPL-2.0\n\n")
	fmt.Fprintf(&b, "// %s from %s/*.yml; DO NOT EDIT.\n\n", generatedCodeMarker, chartSchemasPath)
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n\t\"fmt\"\n\n\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n)\n\n")

	for _, chart := range charts {
		fmt.Fprintf(&b, "const %sName = %q\n", exportedName(chart.Type), chart.Type)
	}
	b.WriteString("\n")

	b.WriteString("func ContentBlocks() map[string]schema.Block {\n\treturn map[string]schema.Block{\n")
	for _, chart := range charts {
		fmt.Fprintf(&b, "\t\t%sName: schema.SingleNestedBlock{MarkdownDescription: %q, Attributes: %sSchemaAttributes()},\n", exportedName(chart.Type), chart.Description, exportedName(chart.Type))
	}
	b.WriteString("\t}\n}\n\n")

	b.WriteString("func NameForElement(tag string) (string, bool) {\n\tswitch tag {\n")
	for _, chart := range charts {
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn %sName, true\n", chart.ElementTag, exportedName(chart.Type))
	}
	b.WriteString("\tdefault:\n\t\treturn \"\", false\n\t}\n}\n\n")
	b.WriteString("func IsSupportedElement(tag string) bool { _, ok := NameForElement(tag); return ok }\n\n")

	b.WriteString("func normalizationRules(tag string) []normalizationRule {\n\tswitch tag {\n")
	for _, chart := range charts {
		if len(chart.Normalizations) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\tcase %q:\n\t\treturn []normalizationRule{\n", chart.ElementTag)
		for _, rule := range chart.Normalizations {
			fmt.Fprintf(&b, "\t\t\t{Kind: %q, Target: []string{%s}, Source: []string{%s}, Unit: []string{%s}, Prefix: []string{%s}, Suffix: []string{%s}},\n", rule.Kind, goStringList(rule.Target), goStringList(rule.Source), goStringList(rule.Unit), goStringList(rule.Prefix), goStringList(rule.Suffix))
		}
		b.WriteString("\t\t}\n")
	}
	b.WriteString("\tdefault:\n\t\treturn nil\n\t}\n}\n\n")

	b.WriteString("// ParseContent parses a recognized chart without mutating spec. TypedSafe is\n")
	b.WriteString("// true only when generated validation passes and rebuilding the model is\n")
	b.WriteString("// semantically identical after the explicitly approved normalizations.\n")
	b.WriteString("func ParseContent(tag string, spec map[string]any) (Entry, ParseMetadata, error) {\n")
	b.WriteString("\tmetadata := ParseMetadata{ElementTag: tag}\n")
	b.WriteString("\tname, ok := NameForElement(tag)\n\tif !ok { return Entry{}, metadata, fmt.Errorf(\"unsupported chart element %q\", tag) }\n")
	b.WriteString("\toriginal := cloneSpecMap(spec)\n")
	b.WriteString("\tmetadata.ValidationErrors = append(metadata.ValidationErrors, validateElementContract(tag, original)...)\n")
	b.WriteString("\tnormalized := cloneSpecMap(original)\n")
	b.WriteString("\tnormalizations, err := applyNormalizations(normalized, normalizationRules(tag))\n")
	b.WriteString("\tif err != nil { return Entry{}, metadata, err }\n\tmetadata.Normalizations = normalizations\n")
	b.WriteString("\tworking := cloneSpecMap(normalized)\n\tvar content Content\n")
	b.WriteString("\tswitch tag {\n")
	for _, chart := range charts {
		fmt.Fprintf(&b, "\tcase %q:\n\t\tmodel, parseErr := Parse%sSpec(working)\n\t\tif parseErr != nil { return Entry{}, metadata, parseErr }\n\t\tcontent = &model\n", chart.ElementTag, exportedName(chart.Type))
	}
	b.WriteString("\t}\n")
	b.WriteString("\tentry := Entry{Name: name, Content: content}\n")
	b.WriteString("\tmetadata.Leftovers = Leftovers(\"\", working)\n")
	b.WriteString("\tmetadata.MissingRequiredFields = content.MissingRequiredFields()\n")
	b.WriteString("\tmetadata.ValidationErrors = append(metadata.ValidationErrors, content.ValidationErrors()...)\n")
	b.WriteString("\tmetadata.Lossless = len(metadata.Leftovers) == 0 && len(metadata.MissingRequiredFields) == 0 && len(metadata.ValidationErrors) == 0 && semanticallyEqualSpec(normalized, content.BuildSpec())\n")
	b.WriteString("\treturn entry, metadata, nil\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("generated content registry does not compile: %w\n\n%s", err, b.String())
	}
	return string(formatted), nil
}

func generateParentBridge(charts []chartInfo, packageName, chartsImport string) (string, error) {
	var b strings.Builder
	b.WriteString("// Copyright Splunk, Inc.\n// SPDX-License-Identifier: MPL-2.0\n\n")
	fmt.Fprintf(&b, "// %s from %s/*.yml; DO NOT EDIT.\n\n", generatedCodeMarker, chartSchemasPath)
	fmt.Fprintf(&b, "package %s\n\n", packageName)
	b.WriteString("import (\n\t\"fmt\"\n\n\t\"")
	b.WriteString(chartsImport)
	b.WriteString("\"\n)\n\n")

	writeChartFields(&b, charts)
	writeParentContainer(&b, "dashifyDashboardContainerModel", true, true)
	writeParentContainer(&b, "dashifySectionContainerModel", false, true)
	writeParentContainer(&b, "dashifyGroupContainerModel", false, false)

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("generated dashboard bridge does not compile: %w\n\n%s", err, b.String())
	}
	return string(formatted), nil
}

// writeChartFields emits the chart block fields shared by every container
// level, embedded by value so the plugin framework promotes their tfsdk tags.
func writeChartFields(b *strings.Builder, charts []chartInfo) {
	b.WriteString("type dashifyChartFields struct {\n")
	for _, chart := range charts {
		fmt.Fprintf(b, "\t%s *charts.%s `tfsdk:%q`\n", exportedName(chart.Type), chart.ModelType, chart.Type)
	}
	b.WriteString("}\n\n")

	b.WriteString("func (f dashifyChartFields) chartEntries() []charts.Entry {\n\tvar entries []charts.Entry\n")
	for _, chart := range charts {
		field := exportedName(chart.Type)
		fmt.Fprintf(b, "\tif f.%s != nil { entries = append(entries, charts.Entry{Name: charts.%sName, Content: f.%s}) }\n", field, field, field)
	}
	b.WriteString("\treturn entries\n}\n\n")

	b.WriteString("func (f *dashifyChartFields) setChartEntries(entries []charts.Entry) error {\n")
	for _, chart := range charts {
		fmt.Fprintf(b, "\tf.%s = nil\n", exportedName(chart.Type))
	}
	b.WriteString("\tfor _, entry := range entries {\n\t\tswitch entry.Name {\n")
	for _, chart := range charts {
		field := exportedName(chart.Type)
		fmt.Fprintf(b, "\t\tcase charts.%sName:\n\t\t\tmodel, ok := entry.Content.(*charts.%s)\n\t\t\tif !ok { return fmt.Errorf(\"chart entry %%q has %%T content, want *charts.%s\", entry.Name, entry.Content) }\n\t\t\tif f.%s != nil { return fmt.Errorf(\"duplicate chart entry %%q\", entry.Name) }\n\t\t\tf.%s = model\n", field, chart.ModelType, chart.ModelType, field, field)
	}
	b.WriteString("\t\tdefault:\n\t\t\treturn fmt.Errorf(\"unsupported chart entry %q\", entry.Name)\n\t\t}\n\t}\n\treturn nil\n}\n\n")
}

func writeParentContainer(b *strings.Builder, typeName string, allowSection, allowGroup bool) {
	fmt.Fprintf(b, "type %s struct {\n", typeName)
	b.WriteString("\tLayout *dashifyLayoutModel `tfsdk:\"layout\"`\n")
	b.WriteString("\tdashifyChartFields\n")
	b.WriteString("\tTemplate *dashifyTemplateModel `tfsdk:\"template\"`\n")
	if allowSection {
		b.WriteString("\tSection *dashifySectionModel `tfsdk:\"section\"`\n")
	}
	if allowGroup {
		b.WriteString("\tGroup *dashifyGroupModel `tfsdk:\"group\"`\n")
	}
	b.WriteString("}\n\n")
}

// --- entrypoint --------------------------------------------------------

var expectedChartFiles = []string{
	"metrics_cluster_map.yml",
	"metrics_list.yml",
	"metrics_single_value.yml",
	"metrics_table.yml",
	"metrics_time_series.yml",
	"text.yml",
}

type generationOptions struct {
	SchemasDir           string
	OutDir               string
	PackageName          string
	BridgePath           string
	LegacyGeneratedPaths []string
	BridgePackage        string
	ChartsImport         string
	Check                bool
}

func runGeneration(options generationOptions) error {
	paths, err := filepath.Glob(filepath.Join(options.SchemasDir, "*.yml"))
	if err != nil {
		return err
	}
	sort.Strings(paths)
	actualFiles := make([]string, len(paths))
	for index, path := range paths {
		actualFiles[index] = filepath.Base(path)
	}
	if strings.Join(actualFiles, "\n") != strings.Join(expectedChartFiles, "\n") {
		return fmt.Errorf("chart schema set is %v; want exactly %v", actualFiles, expectedChartFiles)
	}

	expected := map[string][]byte{}
	charts := make([]chartInfo, 0, len(paths))
	for _, path := range paths {
		source, info, chartErr := generateChart(path, options.PackageName)
		if chartErr != nil {
			return chartErr
		}
		if info.Type != strings.TrimSuffix(filepath.Base(path), ".yml") {
			return fmt.Errorf("%s: type %q must exactly match filename", path, info.Type)
		}
		charts = append(charts, info)
		expected[filepath.Join(options.OutDir, info.Type+"_generated.go")] = []byte(source)
	}
	sort.Slice(charts, func(i, j int) bool { return charts[i].Type < charts[j].Type })
	content, err := generateContentAggregate(charts, options.PackageName)
	if err != nil {
		return err
	}
	expected[filepath.Join(options.OutDir, "content_generated.go")] = []byte(content)
	contracts, err := loadContracts(filepath.Join(options.SchemasDir, "elements"), charts)
	if err != nil {
		return err
	}
	if witnessErr := validateMappingWitnesses(paths, options.SchemasDir, contracts); witnessErr != nil {
		return witnessErr
	}
	contractSource, err := generateContractRegistry(charts, contracts, options.PackageName)
	if err != nil {
		return err
	}
	expected[filepath.Join(options.OutDir, "contract_generated.go")] = []byte(contractSource)
	bridge, err := generateParentBridge(charts, options.BridgePackage, options.ChartsImport)
	if err != nil {
		return err
	}
	expected[options.BridgePath] = []byte(bridge)

	stale, err := obsoleteGeneratedFiles(options.OutDir, expected)
	if err != nil {
		return err
	}
	bridgeDirectory := filepath.Dir(options.BridgePath)
	if filepath.Clean(bridgeDirectory) != filepath.Clean(options.OutDir) {
		parentStale, parentErr := obsoleteGeneratedFiles(bridgeDirectory, expected)
		if parentErr != nil {
			return parentErr
		}
		stale = append(stale, parentStale...)
	}
	legacyStale, err := obsoleteGeneratedPaths(options.LegacyGeneratedPaths, expected)
	if err != nil {
		return err
	}
	stale = append(stale, legacyStale...)
	stale = uniqueSortedPaths(stale)
	if options.Check {
		var problems []string
		for path, want := range expected {
			got, readErr := os.ReadFile(path)
			switch {
			case os.IsNotExist(readErr):
				problems = append(problems, "missing: "+path)
			case readErr != nil:
				return readErr
			case !bytes.Equal(got, want):
				problems = append(problems, "changed: "+path)
			}
		}
		for _, path := range stale {
			problems = append(problems, "obsolete: "+path)
		}
		sort.Strings(problems)
		if len(problems) > 0 {
			return fmt.Errorf("generated chart code is stale:\n  %s\nrun `go run ./%s -mode=write`", strings.Join(problems, "\n  "), chartGeneratorPath)
		}
		return nil
	}

	for path, contents := range expected {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, contents, 0o600); err != nil {
			return fmt.Errorf("writing %s: %w", path, err)
		}
	}
	for _, path := range stale {
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("removing obsolete generated file %s: %w", path, err)
		}
	}
	return nil
}

func obsoleteGeneratedFiles(outDir string, expected map[string][]byte) ([]string, error) {
	entries, err := os.ReadDir(outDir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var obsolete []string
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "_generated.go") {
			continue
		}
		path := filepath.Join(outDir, entry.Name())
		if _, ok := expected[path]; ok {
			continue
		}
		contents, readErr := os.ReadFile(path)
		if readErr != nil {
			return nil, readErr
		}
		if generatedByChartgen(contents) {
			obsolete = append(obsolete, path)
		}
	}
	sort.Strings(obsolete)
	return obsolete, nil
}

func obsoleteGeneratedPaths(paths []string, expected map[string][]byte) ([]string, error) {
	var obsolete []string
	for _, path := range paths {
		if _, ok := expected[path]; ok {
			continue
		}
		contents, err := os.ReadFile(path)
		switch {
		case os.IsNotExist(err):
			continue
		case err != nil:
			return nil, err
		case generatedByChartgen(contents):
			obsolete = append(obsolete, path)
		}
	}
	return uniqueSortedPaths(obsolete), nil
}

func generatedByChartgen(contents []byte) bool {
	return bytes.Contains(contents, []byte(generatedCodeMarker)) ||
		bytes.Contains(contents, []byte(legacyGeneratedCodeMarker))
}

func uniqueSortedPaths(paths []string) []string {
	sort.Strings(paths)
	unique := paths[:0]
	for _, path := range paths {
		if len(unique) == 0 || unique[len(unique)-1] != path {
			unique = append(unique, path)
		}
	}
	return unique
}

// --- helpers -------------------------------------------------------------

func sortedKeys(m map[string]property) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys) // deterministic output, so regenerating without a schema change produces no diff

	return keys
}

func exportedName(snake string) string {
	parts := strings.Split(snake, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}

	return strings.Join(parts, "")
}

func goStringList(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}

	return strings.Join(quoted, ", ")
}
